### ISSUE TITLE
Add help page for project search

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#102]
We need to document somewhere that * can be used as a wildcard, AND for a stricter search, etc.

**Comment by madewild** [comment]
The default boolean operator is AND, so searching for **green carbon** (or **carbon green**) retrieves only documents containing both words in any order. To include also documents containing either word, use **green OR carbon**. You can also search for an exact expression using quotes: **"artificial intelligence"** for instance will look for the sequence in that order. Additionally, you can use the star operator as a wildcard: **govern*** will match government, governing, governors, etc.

**Comment by raphdom** [comment]
done!
