### ISSUE TITLE
Theme filters broken

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#104]
Dennis changed the filter names from "Low carbon economy" to "TO04 Low carbon economy" for instance so the categories on the homepage are broken and return no results. We have to align both

**Comment by D063520** [comment]
I think this is a point for raph ....

**Comment by madewild** [comment]
I discussed with Anne and she says that we can leave the "TO01" codes (as asked by Thierry and Slaven) for now but that in the future we should remove them from the public website and only have them in the professional space. I think the best way would be to keep the current order (non-alphabetical) but without showing the codes in the filters. Will open a separate issue.

**Comment by madewild** [comment]
Fixed since we removed the codes again
