### ISSUE TITLE
Add info about translation in About page

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#111]
We should clarify that we used eTranslation for English labels (titles) and summaries (descriptions), which explains some errors

**Comment by raphdom** [comment]
waiting the phrase to put there....

**Comment by madewild** [comment]
**About translation**

English translations of project titles and descriptions have been performed automatically with [eTranslation](https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eTranslation), the neural machine translation tool of the European Commission. While we strive to offer the best accuracy, some occasional translations may be suboptimal. You are encouraged to report them in order to improve the overall quality of the Kohesio knowledge base.

**Comment by madewild** [comment]
Link missing ;)

**Comment by madewild** [comment]
Now it's good!
