### ISSUE TITLE
Improve Contact link in footer

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#117]
Currently we have mailto:REGIO-EXTERNAL-COMMUNICATION@ec.europa.eu?subject=feedback
Two improvements:

- add a target="_blank" so that Gmail (or other) opens in separate tab
- put "Kohesio feedback" as subject as this is a general functional mailbox not dedicated to Kohesio alone

**Comment by raphdom** [comment]
done, sending to dev...
