### ISSUE TITLE
Sort beneficiaries by all fields

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#119]
Currently beneficiaries cannot be sorted

**Comment by D063520** [comment]
sortable + pagination + better cache

**Comment by AlyHdr** [comment]
used boolean parameters for sorting [orderEuBudget,orderTotalBudget,orderNumProjects] - (true = asc , false = desc).

example request: 
`curl -G localhost:5678/api/dev/facet/eu/search/beneficiaries --data-urlencode 'orderNumProjects=false' --data-urlencode 'limit=15' --data-urlencode 'offset=500'`

**Comment by D063520** [comment]
So it available in the backend, but needs to be implemented in the front-end

**Comment by raphdom** [comment]
Implemented, done!
