### ISSUE TITLE
Unresponsive

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#12]
"When filtering, it happens that the results view is truncated (with both Edge and Chrome, did not try with FF) - (see picture below)"
![view truncated](https://user-images.githubusercontent.com/942488/78769005-03d71b80-798d-11ea-8be5-c61cf9b1d74c.jpg)

**Comment by madewild** [comment]
I also have this issue now unless I unzoom to 80%...

**Comment by raphdom** [comment]
done!
