### ISSUE TITLE
Beneficiary detail page

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#120]

**Comment by D063520** [comment]
Hi Raph,

Ali implemented the API:

curl -G https://kohesio.linkedopendata.eu/api/dev/facet/eu/beneficiary --data-urlencode 'id=https://linkedopendata.eu/entity/Q197108'

the response looks like:

{
"country":"https://linkedopendata.eu/entity/Q25",
"item":"Q197108",
"website":"http://www.thun.cz/",
"images":[
],
"projects":[
{
"project":"https://linkedopendata.eu/entity/Q15385",
"euBudget":51663.18,
"startTime":"2016-06-13",
"label":"Energy savings Thun 1794 a.s. operation Monastery over the Ohří",
"endTime":"2016-10-17",
"budget":172210.6
},
{
"project":"https://linkedopendata.eu/entity/Q9806",
"euBudget":145520.0,
"startTime":"2015-09-01",
"label":"Innovation in production of porcelain products of Thun 1794 a.s. New Role",
"endTime":"2018-08-31",
"budget":582080.0
}
],
"totalBudget":754290.6,
"numberProjects":2,
"maxEndTime":"2018-08-31",
"totalEuBudget":197183.18,
"minStartTime":"2015-09-01",
"beneficiaryLabel":"Thun 1794"
}

So there is general information about the beneficiary (name, image, website, country), some statistics (total buget, number projects, ) and the project it got ...

**Comment by raphdom** [comment]
Hello Dennis,

The first beneficiary detail page is on dev.

Can you please send me the country code (exactly the same way that you did in the beneficiaries list)

Regards,

Raphael

**Comment by D063520** [comment]
ah cool! I added the country code and also the geo-coorinates. Note there is also a description field, there was a bug previewsly. For an example see:

https://dev.kohesio.eu/beneficiaries/Q226000

Salut
Dennis

**Comment by raphdom** [comment]
Thanks for the country code. Now I've updated with the country, description and the geo-coordinate.

Thanks

Raphael

**Comment by madewild** [comment]
@D063520 can you send in the API the projects of the beneficiary already sorted by decreasing EU contribution, like we have on the global beneficiary page? Later on we will also need to add the options for the user to sort them differently...

**Comment by D063520** [comment]
ok, done

**Comment by D063520** [comment]
found a little bug, for this beneficary:

https://dev.kohesio.eu/beneficiaries/Q206

the map is not centered ....

**Comment by D063520** [comment]
not sure what you think, but one could aggregate the projects of one beneficary on a map ..... then there is a map even if we do not have the geo-coordianates of the beneficary
PS: could also go wrong when they indicated the address of the beneficary and not the one of the projects

**Comment by raphdom** [comment]
fixed

**Comment by madewild** [comment]
is this issue still open for some reason?

**Comment by raphdom** [comment]
it was only the first version but if you are okay guys with this we can close and open others if needed?

**Comment by madewild** [comment]
@gachpas can you have a look and check if we miss some information of the beneficiary detail page?

**Comment by D063520** [comment]
I limited the number of projects displayed per beneficary to 1000. otherwise there was a performance issue

**Comment by madewild** [comment]
We probably will need some king of pagination there too...

**Comment by gachpas** [comment]
Thanks guys ;)
Fully agree with Max concerning the pagination.
I will review this together with the team and will come back to you :)
Br

**Comment by madewild** [comment]
after discussion with @gachpas we can close this now and will reopen later if needed when they have time for an in-depth review
