### ISSUE TITLE
When project selected on the map do not load the full application again

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#123]
Hi Raph,

it would be nice if you can fix this too ....

Salut
Dennis

**Comment by D063520** [comment]
I put it in v3, if you do not make it for this is not a problem ......

**Comment by raphdom** [comment]
yeah. I will try to do this for next week. It is not simple because the map using leaflet is out of the angular scope, I need to use dynamic components in angular to solve that.

**Comment by raphdom** [comment]
finally done!
