### ISSUE TITLE
Social network links

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#127]
Some remarks about the links we find on a detail page like https://kohesio.eu/projects/Q141625

- I would remove the colon (:) after SHARE
- all links should open in target="blank"
- dribbble.com/ should be https://dribbble.com/
- https://kohesio.eu/rss redirects to https://kohesio.eu/404
- finally, we could use some extra arguments like ?text= and ?u= as shown on https://sproutsocial.com/insights/social-media-shares/ for instance, in order to facilitate direct sharing of the project and not just link to the social media platform

**Comment by teodoracostin** [comment]
Hi Max,

Do we know what will be the final links for Khoesio social sharing? What we have now it is just an example I have added. 
Are we going to keep all of them?

**Comment by madewild** [comment]
@teodoracostin  no idea, I guees you should check with the communication team in REGIO (Amaury/Slaven)...

**Comment by teodoracostin** [comment]
@madewild will check with Pascal tomorrow (will be back from holiday)
