### ISSUE TITLE
Wrong numbers in themes on homepage

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#129]
For instance Low Carbon Economy shows "17 302 projects" whereas we have 17 547 on https://kohesio.eu/projects?theme=Low-Carbon-Economy
Are the numbers on the homepage static? If yes we should make them dynamic with an API. If not there is something wrong with the query behind...

**Comment by D063520** [comment]
hi Raph, this is done on the API side .... if you now call the statistics API: 

https://kohesio.linkedopendata.eu/api/facet/eu/statistics 

you will get also the themes statistics for the first page ...

**Comment by raphdom** [comment]
this is done
