### ISSUE TITLE
Remove three dots (...) for short summaries

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#13]
Don't show the three dots at the end of the summary if it is shorter than the text length limit.
For instance it should be "DELTA GREEN" and not "DELTA GREEN..."
![dots](https://user-images.githubusercontent.com/942488/79213905-46479f00-7e4a-11ea-8517-3f4fc6402b1e.png)

**Comment by madewild** [comment]
Also in labels (titles)

**Comment by raphdom** [comment]
Done
