### ISSUE TITLE
Enable download of projects via csv and excel

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#136]
I added APIs similarly to beneficiaries for the exports. 

/facet/eu/search/project/excel 

and

/facet/eu/search/project/csv

**Comment by madewild** [comment]
@D063520 please ensure that the format is XLSX and not XLS

**Comment by D063520** [comment]
This is fixed in the backend, it needs to be fixed in the front-end

**Comment by raphdom** [comment]
fixed
