### ISSUE TITLE
Export beneficiaries (and project) to XLSX

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#151]
Hola!

the exports for beneficiaries (and projects, not implemented yet in the UI) in DEV return now xlsx. When I use the download button the name seams to be overwritten by the UI from xlsx to xls.

Salut
Dennis

**Comment by raphdom** [comment]
It is implemented on client side for projects page, but now I have an error in the API, can you check, please?

**Comment by D063520** [comment]
yep, my bug, it is working now .... but still there is the problem that the generated file is xls and not xlsx. The API produces filename="beneficiary_export.xlsx". So something in the front-end is happening I guess ....

**Comment by raphdom** [comment]
done, the front-end now is exporting to xlsx
