### ISSUE TITLE
Scrolling past the map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#158]
Not always easy to scroll down the screen when the map occupies most of the screen…then you easily scroll the map instead of the page.

**Comment by teodoracostin** [comment]
Fixed.

**Comment by madewild** [comment]
OK for this version but could be improved later...

**Comment by raphdom** [comment]
we could add a layer and just when the user click on the map start the interaction with the map. With this we prevent the wrong scrolling...

**Comment by raphdom** [comment]
I was searching the best option for this and find better to disabled the dragrable function on the map on mobile, if the user want to zoom in and out or pan he can use two fingers, I think it is more natural and doesn't require one more click to start the map navigation. It is already on dev. What you think?

**Comment by madewild** [comment]
@gachpas can you test and give your feedback?

**Comment by gachpas** [comment]
@madewild, much better like that ;)
Thanks @raphdom

and Happy New Year to both of you, as well as your families ;)

**Comment by raphdom** [comment]
Happy new year too. I will close this issue. Thanks
