### ISSUE TITLE
Implement better collapsible refine search menu

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#164]
When having a result page, the page should be opened by default with the filtering criteria closed, so that the results appear first and the little arrow to open the filtering criteria should be a small button named Refine search, which when clicking on would open the filtering possibilities.

**Comment by raphdom** [comment]
we will split this in 2. The search panel is collapsible on mobile, but to put the label "refine search" we will need more time, because it is not customizable on eui.

**Comment by madewild** [comment]
The search menu is not very visible and the arrow is too far, to improve later...

**Comment by raphdom** [comment]
fixed
