### ISSUE TITLE
Losing navigation via the map when clicking on a result

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#175]
As already discussed in the past, when consulting results of a search and clicking a result, one was loosing the search criteria when going back. The same happens when navigating thorugh the map...when arriving to a location dot and clicking on a result, the navigation is lots and you are sent back to the whole Europa map when going back.
It is not user-friendly :(

**Comment by madewild** [comment]
Thanks @gachpas for reporting here! :)

**Comment by madewild** [comment]
Not easy because the zoom in the map is not changing the URL...

**Comment by gachpas** [comment]
@madewild, easier for all ;) I have suggested to Anne that she also creates a profile ;)

**Comment by gachpas** [comment]
maybe by opening in another tab then ?

**Comment by madewild** [comment]
Opening in a new tab is usually not considered a good practice for UX when staying on the same website.
We will discuss and try to find an appropriate solution.

**Comment by gachpas** [comment]
if we can solve that behaviour without opening another tab, it is perfect.
If not, between losing the search criteria and having another tab opened, as a user, my choice is quickly done ;)

**Comment by raphdom** [comment]
One possible solution that should be the better one is add a popup when the user click in the point, this popup will be exactly the same of the detail page. With this we don't lose the navigation in the map, the user can close the popup and continue the navigation.

**Comment by gachpas** [comment]
Hello @raphdom,
so this popup would +/- act as a new tab, right? Just to see if I understood correctly :)
Br,
Pascal

**Comment by raphdom** [comment]
No, not a new tab but a modal window that will cover the whole page for mobile and part of the page on desktop, we will have a close button and a button to open in new tab. I am going to implement it on dev to check the behavior...

**Comment by gachpas** [comment]
OK. Thanks @raphdom ;)

**Comment by raphdom** [comment]
done, you can check if it is okay for you we can close the issue @gachpas and @madewild

**Comment by gachpas** [comment]
Thanks @raphdom. 

It is ok, except that the "Open in a new tab" did not work (tested with Safari on iPhone 7)

Br,
Pascal

**Comment by raphdom** [comment]
I've tried Chrome on IPhone XR and it works, normally should work because it is a native javascript code, can you try to delete the cache in the browser and try again, please?

**Comment by madewild** [comment]
I tried in Chrome with developers tools and it also does not work for me: the new tab opens but the URL is https://q2496120/ (404 error) instead of https://kohesio.eu/projects/Q2496120 for instance. I cleaned the cache and it did not help. The Edit link going to https://linkedopendata.eu/wiki/Item:Q2496120 works well.

**Comment by raphdom** [comment]
I know, you are in the homepage, I was thinking in the project page, but indeed we have a problem in the homepage, I will fix it. Thanks

**Comment by raphdom** [comment]
fixed

**Comment by gachpas** [comment]
Thanks @raphdom
