### ISSUE TITLE
Near me feature icon

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#177]
You have changed the NEar me button into a House logo.
If I understand the reason behind, in terms of user experience, it looks more like a Home page button to me. If the idea is to gain space, one could imagine a geolocation icon (if you see what I mean ;o) Other wise, coming back to "Near me" even with smaller font is also good

**Comment by raphdom** [comment]
I've changed the icon to a map marker.

**Comment by gachpas** [comment]
Thanks @raphdom. Ok for me ;)
