### ISSUE TITLE
Breadcrumb in the map preventing clicking on results

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#178]
Sometimes when digging into the map, when the list of results is long, you cannot click on the first results. They are a bit hidden by the breadcrumb and their clicking area is not usable.

**Comment by madewild** [comment]
![Uploading bcmap.png…]()

**Comment by madewild** [comment]
![bcmap](https://user-images.githubusercontent.com/942488/102329312-8b4b4480-3f88-11eb-97e3-0dd6123e88fd.png)

**Comment by madewild** [comment]
@gachpas two solutions:
- close the breadcrumb of the map
- swipe the map to display the top of results
![swipe](https://user-images.githubusercontent.com/942488/102329504-c8173b80-3f88-11eb-899a-fc700d4eeb4e.png)

Can you try and tell us if it's enough? Difficult to find a workaround. There is also a scrollbar in the list of results but it only appears when you start scrolling.

**Comment by gachpas** [comment]
Hello @madewild,

I would let the breadcrumb, rather have a popup with the list of projects (which occupies the whole screen) and click the cross to close it and come back to the map.

Is this feasible?

Thanks and Kr,
Pascal

**Comment by madewild** [comment]
@gachpas this is already the current behaviour, except that the popup does not fill the whole screen. Even if we enlarge there is no guarrantee that we can show all if there are too many projects... maybe we actually need a smaller popup to be sure that the top is not over the map limit, forcing the user to swipe the map down...

**Comment by madewild** [comment]
OK @gachpas was thinking of a full layer hiding the map and displaying only the results
example on https://webgate.ec.europa.eu/esiflegislation/display/ESIFLEG/ESIF+Legislation+Home (mobile version, when clicking the magnifying glass search icon)
@raphdom let's discuss the options

**Comment by raphdom** [comment]
okay, I've committed one version that I did some improvements, I don't like to expand to the fullscreen the popup because in the user experience perspective he lose the map and sometimes the user click by mistake in one point and he would like to click in one very close. If we put a popup that cover all the screen when the user close it than he doesn't know which point he clicked before.

**Comment by gachpas** [comment]
Thanks @raphdom. It is acceptable as is. Not the perfect navigation experience (when moving the card at the dots level) but a good compromise for the pilot. Thanks and kr
