### ISSUE TITLE
Professional space link not correct

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#189]
When clicking on professional space, I land here instead of directly into the sheet:

![sheet_not_found](https://user-images.githubusercontent.com/942488/100332478-bb2eaa00-2fd1-11eb-9ba4-f250dbf51e03.PNG)

To check with Catia

**Comment by raphdom** [comment]
can you point the right link please?

**Comment by madewild** [comment]
I think we should go the the root of the stream: https://intragate.development.ec.europa.eu/qs_cnect_audit_hub_vp/ecas/hub/stream/c64d563e-d9c9-4e7d-8794-914cd8964567
please cross-check with Catia...

**Comment by raphdom** [comment]
discussed with Catia and change to this link that you indicated, to the stream.
