### ISSUE TITLE
Kohesio mobile dark mode

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#192]
Hello,

We have received a comment from a colleague in REGIO.A2 Relations with MS (Amaury) that the dark mode is not working ok for Kohesio mobile.

Is it something that has been conidered yet?

Nothing urgent but to be taken on board when moving to the project phase ;)

Br,
Pascal

**Comment by madewild** [comment]
Dark mode is currently not a priority, closing.
