### ISSUE TITLE
Social media sharing buttons

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#198]
When clicking on email, the link is copied into an email that is automatically opened in your mailbox; This is the expected behaviour.
Howevere, when clicking on th eother buttons 5Linkedin, FB, ...), it just open the paltform but dos not create any link or post.
Is it the "normal" behaviour?

**Comment by madewild** [comment]
No indeed, this should be improved with a draft publication for each social media platform.

**Comment by madewild** [comment]
for the linkedin button please use this link: https://www.linkedin.com/feed/hashtag/euinmyregion/

**Comment by madewild** [comment]
(for linkedin link, also in footer button of homepage)

**Comment by gachpas** [comment]
Hello @madewild , not sure I understand your comment? my initial comment was on the share, saying that it just open the app, but does not copy the link to the Kohesio page.

**Comment by madewild** [comment]
Indeed, I will split into two issues

**Comment by madewild** [comment]
Related issue with linkedin button on homepage: #215

**Comment by raphdom** [comment]
Instagram does not support the share url, for all the others it will be implemented

**Comment by raphdom** [comment]
Fixed, can you check on dev, please?

**Comment by gachpas** [comment]
@madewild , @raphdom , It is ok. Thanks ;)
