### ISSUE TITLE
Audio-visual content not displayed

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#199]
the pics are not displayed into the audio-visual section (except one), nor in the project fiche 
This happens with Edge; no problem with Chrome

**Comment by madewild** [comment]
Kohesio does not officially support Edge, the recommended browsers are Chrome/Firefox. Let's see if there is a quick fix but if not I would suggest ignoring it for now since Microsoft announced they would rebuild Edge on top on Chromium (the open source project behind Chrome) which should solve such issues.

**Comment by madewild** [comment]
Yeah @AThollard joined GitHub!

**Comment by madewild** [comment]
I'm just wondering, should we not also put the images here:
![avmat](https://user-images.githubusercontent.com/942488/110762302-ee2f3d80-8250-11eb-8d10-044f38daf8a6.png)

or hide this unused section?

**Comment by AThollard** [comment]
Yes we were supposed to display the audiovisual material there. I would indeed hide it and re-discuss with our colleagues from the business to fine tune their needs for the next steps (and also plan it)

**Comment by gachpas** [comment]
The idea was also to allow MA to upload their own audio-visual material to complete what we have.
Communication campaign is something different, which will be used by REGIO colleagues and/or MAs.
I am not usre whether we should hide it, as for instance we have already communication campaigns that we could share....also, it is good to show the potential...TBD

**Comment by AThollard** [comment]
Indeed @gachpas but as discussed yesterday, we also have to check the IP / creative common licenses issues before. And regarding the campaigns, again to be discussed with our colleagues because most of the time campaigns spots entire regions so how to aggregate at projects level?

**Comment by gachpas** [comment]
Hello @AThollard, for the CCL, the comment is valid even if what we share now in terms of pictures. For the campaigns, we will indeed discuss with the colleagues...one solution could be to link the video about a programme to all concerned projects...but to be checked with Alex's team :)

**Comment by raphdom** [comment]
I will hide this section for now. If we need to implement in the future we will create another issue. Thank you all.
