### ISSUE TITLE
Add "in progress" icon when searching

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#200]
I have experienced very slow calculation before the result is dispayed when sortering or filterng the beneficiaries.
As there is no visual that shows that the system is working, you have the impression that there is no result or that the system is blocked.

**Comment by madewild** [comment]
@D063520 @AlyHdr can the requests be further optimized? If not, we could indeed put a "busy" symbol while it's running.

**Comment by D063520** [comment]
it depends, some things we are caching ..... others not, in fact we try to cache the heavy things .... could you please always indicate the request .... the it is easier to debug
PS: in general we noticed that there is some problem and we were working on the cache

**Comment by gachpas** [comment]
Hi @D063520, in fact , it was basically all the requests done to filter or sort. 
I started with the sort, and nothing seemed to move... then I wait more time and saw the change..then when I start again the same procedure, it was faster (maybe in cache) but after it started again to be slow...I know that I madeCTLR+F5  but I cannot remember at what stage of that process.

As proposed by @madewild, having some sort of "in progress" visual when calculatiing would already help...

Thanks and kr,
Pascal

**Comment by D063520** [comment]
Hi,

so when you do CTLR+F5  you will not clean the cache I mean ... it is in the backend. We recompute the cache every night. So when you see a slow request, please note it down and we will check ....

in general currenlty I know the situation is not ideal since we had a bug on the cache level .....

**Comment by gachpas** [comment]
of course, I was just mentioning the CTLR+F5, as an extra info for your analysis ;)

**Comment by madewild** [comment]
fast enough, closing for now
