### ISSUE TITLE
Pagination of results limited to 1000

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#201]
This is a known issue that I log just for tracking and eventual improvement during the project phase.

the fact that the pagination sown cannot be navigated till the end (e.g. when showing 1759 results, just the results till 1005 are displayed. If you try to go to the next page, it says "no results".

**Comment by madewild** [comment]
We have indeed an arbitrary limit at 1000 for performance reasons. Let's see what we can do to improve in the future, at least put a message friendlier than "no results".

**Comment by D063520** [comment]
@AlyHdr can you check this please .... there is a bug there, after 1000 it should be slow but not return no results
PS: would have never thought that someone clicks until 1000

**Comment by AlyHdr** [comment]
@D063520 I found the bug and I pushed the changes to dev. It's working now however those after 1000 would take time and in the UI there is nothing that pops up as it's running the query or something so it looks like it's stuck.. Maybe a loading signal in the corner would be nice..

**Comment by AlyHdr** [comment]
BTW nobody show results more than 500, checkout amazon for example.. they just show the first 7 pages which is basically almost ~300 hits.. you can not even go further
https://www.amazon.fr/s?k=blanket&__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&ref=nb_sb_noss_1

**Comment by madewild** [comment]
@gachpas is the current behaviour ok or still needs improvement?

**Comment by gachpas** [comment]
Hello @madewild, Have you changed something or it is still the exact same behaviour as reported?

**Comment by D063520** [comment]
@gachpas can you try again and paste an example .... I'm not sure anymore ....

**Comment by madewild** [comment]
@AlyHdr reported debugging and improvements. It works for me with small delay:
![1000](https://user-images.githubusercontent.com/942488/117290508-2c6e6500-ae6e-11eb-8cd8-585b0aec9bf0.png)

**Comment by gachpas** [comment]
@D063520 Hi Denis, should I try in dev or Prod?

**Comment by D063520** [comment]
Both are fine. And yes, basically if I remember correctly it should work but there is a delay, because the result is not cached (we saw it as something improbable).

**Comment by madewild** [comment]
For me it's perfectly acceptable, I would close it if @gachpas confirms :)

**Comment by gachpas** [comment]
Yes, please proceed with closing :)
