### ISSUE TITLE
problem with special characters in beneficiary text

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#203]
See for example:

https://dev.kohesio.eu/beneficiaries/Q226000

There are characters like \n\n

**Comment by madewild** [comment]
@D063520 I don't see any newline chars on this link, can you be more specific or add a screenshot?

**Comment by D063520** [comment]
this is a good example
https://dev.kohesio.eu/beneficiaries/Q39
basically the json wtring is rendered an not parsed before

**Comment by raphdom** [comment]
there is something wrong with this string that is coming from the server:

![image](https://user-images.githubusercontent.com/5124917/110633236-d0a69900-81a8-11eb-8dd9-d98713c840c3.png)

In the beginning of the string we have double quotes, and should be \" if you want to represent a double quote inside the string. If you fix this everything should work properly.

**Comment by D063520** [comment]
@AlyHdr: ali can you check this, it is our problem ....

**Comment by AlyHdr** [comment]
I think it should be fine now.. just on dev https://dev.kohesio.eu/beneficiaries/Q39
