### ISSUE TITLE
email adress behind the contact 

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#204]
the email adress behind contact button had been provided and (if I remember correctly implemented) but is now not available in test and prod.

Here it is: REGIO-EXTERNAL-COMMUNICATION@ec.europa.eu

Thansk and Kr,
Pascal

**Comment by gachpas** [comment]
Sorry, I cannot update the ticket......

so I place the énd related request here:  
for the linkedin button please  use this link: https://www.linkedin.com/feed/hashtag/euinmyregion/

**Comment by madewild** [comment]
@gachpas I moved the Linkedin part to #127

**Comment by madewild** [comment]
For the email address, it's implemented behind the "contact" word but not behind the envoloppe icon
@raphdom can you take care of this?

**Comment by raphdom** [comment]
fixed on dev
