### ISSUE TITLE
Add fund information to beneficiary

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#205]
Two additional informations to provide on beneficiary detail page:
- total amount per fund (ERDF/ESF/YEI...)
- fund for each project listed
To be added first in the API then shown on the website.

**Comment by madewild** [comment]
@D063520 this is already provided by the API?

**Comment by madewild** [comment]
@D063520 what's the status of this?

**Comment by raphdom** [comment]
@D063520 need to know what's the name of each field in order to add in the ui.

**Comment by D063520** [comment]
the fund for each project is already there, Ali will add the budegt per fund

**Comment by madewild** [comment]
@raphdom the field you need is "fundLabel" for each project (on https://dev.kohesio.eu/beneficiaries/Q2514974 for instance), to be added to each project in the table

**Comment by AlyHdr** [comment]
The API now returns a list of budgetsPerFund like so:

<img width="768" alt="Screenshot 2021-09-22 at 14 23 17" src="https://user-images.githubusercontent.com/43681203/134343087-6a004ac3-d88d-4d0d-811e-2f981701be8a.png">

Example of a given project:

https://dev.kohesio.linkedopendata.eu/api/facet/eu/beneficiary?id=https://linkedopendata.eu/entity/Q2514974

**Comment by raphdom** [comment]
@AlyHdr thank you. Can I ask you 2 things. Instead of "n/a"can you put "Other funds"? And sort the totalBudget desc ?

**Comment by madewild** [comment]
Actually by totalEuBudget desc. The totalBudget is irrelevant here and should not be shown at all in my opinion.

**Comment by AlyHdr** [comment]
@raphdom It must be done now

**Comment by raphdom** [comment]
Thanks @AlyHdr. @madewild can you test on dev?

**Comment by madewild** [comment]
Perfect, thank you both!
Of interest for @roberto-musmeci @AThollard @gachpas (check https://dev.kohesio.eu/beneficiaries/Q2514974 for instance)
Closing this now, feel free to reopen if something is wrong/missing.

**Comment by madewild** [comment]
Some slight issue with zero values on https://dev.kohesio.eu/beneficiaries/Q2823834
Should be:
Funded by EU: n/a

funds
ERDF: n/a
ESF: n/a
CF: n/a

**Comment by gachpas** [comment]
Hello @madewild, 

linked to this:
https://dev.kohesio.eu/beneficiaries/Q2825030
funds
IPA II: 0,00 €
ERDF: 0,00 €
ESF: 0,00 €
CF: 0,00 €

We do not have EU allocations for those projects and n/a is returned, so why the summary gives a value 0 and not n/a?

Br,
Pascal

**Comment by madewild** [comment]
That's exactly what I wrote above! :D

**Comment by gachpas** [comment]
oops ;)

**Comment by raphdom** [comment]
fixed, @madewild can you check and close the issue, please?

**Comment by madewild** [comment]
Perfect.
