### ISSUE TITLE
Intervention field dropdown too large

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#212]
![intervention_field](https://user-images.githubusercontent.com/942488/111119763-cd295e00-856a-11eb-8fee-61f345dc268f.png)

can we have an automatic carriage return for long titles? or use "..." after a limit of 200 chars for instance ?

**Comment by D063520** [comment]
I made it in the backend for now .....

**Comment by raphdom** [comment]
fixed, on dev
