### ISSUE TITLE
Adapt Linkedin button

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#215]
Link to https://www.linkedin.com/feed/hashtag/euinmyregion/ instead of generic https://www.linkedin.com/ (in homepage footer and maybe elsewhere)

**Comment by madewild** [comment]
Duplicate of #198

**Comment by madewild** [comment]
also on detail pages

**Comment by raphdom** [comment]
I've changed on homepage, 

In the details page (project and beneficiary) for me make sense to be the linkedin for each project/beneficiary, I mean not only for linkedin, should all the social icons pointing to their social account, non?

**Comment by madewild** [comment]
OK fine, I close this one then and leave #127 for the rest
