### ISSUE TITLE
Adding countries in the backend + flags

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#219]
There is an API to grab the countries for this facet:

<img width="373" alt="Screenshot 2021-05-21 at 11 29 42" src="https://user-images.githubusercontent.com/10883585/119116054-29f03b80-ba28-11eb-8bc2-8bd1962d870e.png">

here

https://dev.kohesio.linkedopendata.eu/swagger-ui.html#/facet-controller/facetEuCountriesUsingGET

Can you please use this so that I can add countries in the backend?

Salut
Dennis

**Comment by madewild** [comment]
This is only in dev now? Or can already be implemented in prod? We need to be careful that Sweden does not show in the list in prod...

**Comment by D063520** [comment]
yes, we implement it in dev.kohesio.eu and in dev.kohesio.linkedopendata.eu. So it will be only in DEV and it will move to PROD once we move DEV to PROD.

**Comment by madewild** [comment]
@raphdom when you have time this would be the most urgent issue to fix...

**Comment by raphdom** [comment]
it is fixed, but we need to double check (specially the map) when we will add a new country.

**Comment by madewild** [comment]
@raphdom in dev we already added 3 more countries so we can check

**Comment by D063520** [comment]
yes, can you check dev.kohesio? I noticed that the flag of the countries are not there .... I can provide you the flags if you want ...

**Comment by madewild** [comment]
+ benef dropdown of countries

**Comment by madewild** [comment]
seems fine
