### ISSUE TITLE
Link from project to beneficiary

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#221]
On the project detail page, there is this info:

beneficiary
Name: XXX
Website: YYY

The link behind the name should now be systematic and redirect to the corresponding beneficiary detail page (which did not exist yet at the time) and not anymore to Wikidata. We can remove the link to Wikidata and also the disclaimer about leaving the Kohesio website.

Additionally, the website should be on the beneficiary detail page and not on the project detail page. When there is none we can just hide it and not show "n/a".

**Comment by madewild** [comment]
also remove "Name", just name of benef with link to benef detail page

**Comment by raphdom** [comment]
fixed on dev

**Comment by madewild** [comment]
perfect!
