### ISSUE TITLE
Add button to visualise graph

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#223]
On each project and beneficiary detail page, add a link to visualise in the knowledge graph (to open in a new tab). Maybe next to "edit"?

Link should be https://query.linkedopendata.eu/#%23defaultView%3AGraph%0ASELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20VALUES%20%3Fitem%20%7B%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ198964%3E%7D%20%3Fitem%20%3FpDirect%20%3FlinkTo%20.%0A%20%20%3Fitem%20rdfs%3Alabel%20%3FitemLabel%20.%0A%20%20FILTER%28lang%28%3FitemLabel%29%3D%22en%22%29%0A%7D

but the qid (here Q198964) needs to be replaced by the qid of the project/beneficiary

**Comment by madewild** [comment]
should be like https://tinyurl.com/ydvr5ta9

**Comment by madewild** [comment]
https://query.linkedopendata.eu/embed.html#%23defaultView%3AGraph%0ASELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20VALUES%20%3Fitem%20%7B%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ198964%3E%7D%20%3Fitem%20%3FpDirect%20%3FlinkTo%20.%0A%20%20%3Fitem%20rdfs%3Alabel%20%3FitemLabel%20.%0A%20%20FILTER(lang(%3FitemLabel)%3D%22en%22)%0A%7D

**Comment by madewild** [comment]
@raphdom nice for projects but now we need the same for beneficiaries on the detail page, e.g. https://dev.kohesio.eu/beneficiaries/Q198964

**Comment by raphdom** [comment]
fixed on dev

**Comment by madewild** [comment]
Nice, @raphdom for consistency I would just order the buttons in the same way (for projects it's Graph then Edit, for beneficiaries it's Edit then Graph). No preference, just please harmonise it. :)

**Comment by raphdom** [comment]
harmonized... :)

**Comment by madewild** [comment]
okido
