### ISSUE TITLE
Show multiple beneficiaries on project detail page

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#224]
Currently it shows one random beneficiary among several if there are more than one

e.g. https://kohesio.eu/projects/Q2024527

**Comment by D063520** [comment]
Looks like a problem in the UI, the API looks good:

<img width="1679" alt="Screenshot 2021-06-14 at 15 37 18" src="https://user-images.githubusercontent.com/10883585/121901111-690f6500-cd26-11eb-8ac6-06d5fcf5fa6c.png">

**Comment by madewild** [comment]
Yes I assigned to Raph... Normally there is only one beneficiary so we did not foresee to show several

**Comment by raphdom** [comment]
fixed on dev

**Comment by madewild** [comment]
Thanks @raphdom, could you just sort them alphabetically? The order is random and changes when we refresh the page...

**Comment by raphdom** [comment]
sorted. Can you test please?

**Comment by madewild** [comment]
excellent!
