### ISSUE TITLE
Missing EU contribution should be shown as unknown or n/a

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#227]
For Greek projects we don't have the EU contribution at this stage.
The rendering on e.g. https://dev.kohesio.eu/projects/Q2814985 is strange: "Funded by EU: (80%)"
Should be "Funded by EU: unknown (80%)" or similar.
We cannot compute it by multiplying the total budget by 80% because the percentage is an average at priority axis level...

**Comment by raphdom** [comment]
on dev
