### ISSUE TITLE
Slow rendering of dense project points

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#228]
I noticed that when there is a point with man y projects it takes quite a while to show the project list window.
<img width="1390" alt="Screenshot 2021-07-07 at 18 42 15" src="https://user-images.githubusercontent.com/10883585/124798056-3cc8bc00-df53-11eb-9de5-2c8aecb8482f.png">
 @raphdom can you try to check ... the API might also not be super fast but even the second time when the result is cached it takes quite a while. I think it is nearly impossible to optimise this in the backend so I would try to get out of the front-end as much as we can ....
PS you can try with Zagreb (in Croatia)

**Comment by madewild** [comment]
I checked and for me it's quite fast, and for @raphdom too...

**Comment by madewild** [comment]
@D063520 do you still experience the issue? I looked at Zagreb again and it loads in 1 second

**Comment by D063520** [comment]
https://blog.bitsrc.io/3-ways-to-render-large-lists-in-angular-9f4dcb9b65

**Comment by madewild** [comment]
let's investigate later

**Comment by raphdom** [comment]
@D063520 Like max said, for me it is very fast on Zagreb(Croatia). 2000 items on a list it is not so many for me that justify the implementation of techniques likes virtual scrolling or others.

**Comment by madewild** [comment]
cannot reproduce, feel free to reopen if happening again
