### ISSUE TITLE
Show total budget instead of EU contrib in project list (results)

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#229]
@AThollard : Investigate if it worth leaving the EU budget on the project summary when at least 2 countries are not providing it (Greece / Portugal).
@D063520 : I would suggest using in the general presentation the global budget (since it is always provided) but for the project view to display it. If it is not there then indicate that it is not provided by the member state.
@AThollard : Agreed. Let's check with @slaven777 @Bisiaam @gachpas @roberto-musmeci

**Comment by gachpas** [comment]
@AThollard , my 2 cents on this...
for me, as a citizen, this is crucial...when loking for projects in my region, it is maybe the first info my eyes will catch and what finally matters. Only after I would see what is the topic. So I would definitively keep it and, as proposed by Denis, indicate when it is not provided.

This being said, I have to admit that it would also be weird for a citizen to understand why the EC cannot determine the amount of money that it gives to a certain project...so maybe we should phrase it carefully.

**Comment by D063520** [comment]
@slaven777: can we use this a bit as a pressure and ask again to greece and portugal if they can provide this data ....

**Comment by madewild** [comment]
leaving like this for the moment, will adapt for next programming period if needed

**Comment by AThollard** [comment]
ok
