### ISSUE TITLE
One click on the beneficiary link in project details does not open

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio.eu#230]
If you single click on the beneficiary name it does not open. You have to use right click -> open in a new tab

**Comment by madewild** [comment]
From a standard page like https://dev.kohesio.eu/projects/Q139379 it works correctly, right?
But from the overlay project detail page (starting from the homepage map), clicking on the beneficiary name opens the beneficiary page behind the overlay which is strange...
@AThollard could you confirm this is the issue?
@raphdom could the beneficiary detail page open in overlay and replace the project in this case? or another fix?

**Comment by raphdom** [comment]
okay, understand, normally it will be better to open in a new tab when the click comes from the overlay, because if it will be in the same page the user cannot use the back button, and inside the overlay is weird

**Comment by madewild** [comment]
okay perfect, you can open the beneficiary in a new tab by default when coming from the overlay then

**Comment by raphdom** [comment]
it was applied like that on dev

**Comment by madewild** [comment]
perfect!
