### ISSUE TITLE
cannot click on region of Portugal

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#231]
the region "Norte region" seams covered by the "projects nearme"button ...

<img width="1390" alt="Screenshot 2021-07-09 at 11 24 48" src="https://user-images.githubusercontent.com/10883585/125056214-4ca5e480-e0a8-11eb-8844-ccc819122cb4.png">

<img width="1390" alt="Screenshot 2021-07-09 at 11 24 54" src="https://user-images.githubusercontent.com/10883585/125056208-4adc2100-e0a8-11eb-890c-6c127be80c17.png">

**Comment by raphdom** [comment]
yes, you can just swipe the map and click in the region, I think this is not a problem.

**Comment by D063520** [comment]
I think it's not very intuitive .... for a "normal user" I think it looks wrong (but I agree I'm very picky here ....)

**Comment by madewild** [comment]
OK not urgent but this is the default view for Portugal so could be improved later if possible...

**Comment by madewild** [comment]
ok understood, not linked to the button but to a div map.navigation that is over the actual map

**Comment by madewild** [comment]
Perfect now!
