### ISSUE TITLE
map breadcrump disappearing

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#232]
click on denmark and then on a project, then the breadcrump is dissapiring

before:
<img width="1390" alt="Screenshot 2021-07-09 at 11 28 04" src="https://user-images.githubusercontent.com/10883585/125056702-c76eff80-e0a8-11eb-8b31-114123d771de.png">
after: 
<img width="1390" alt="Screenshot 2021-07-09 at 11 28 10" src="https://user-images.githubusercontent.com/10883585/125056663-bf16c480-e0a8-11eb-9959-275e0d822011.png">

**Comment by raphdom** [comment]
the breadcrumb does not disappear, normally when we have small screens I just minimize the breadcrumb to not take the entire screen, if you click in the arrow to the right should appear again.

**Comment by D063520** [comment]
I think it is not very intuitive .... as you want .....

**Comment by madewild** [comment]
But the breadcrumb also minimizes on my 27" screen...

**Comment by madewild** [comment]
OK not urgent anyway

**Comment by raphdom** [comment]
It was fixed that now the breadcrumb only collapse in mobile version. @madewild I cannot ask you to check... :)

**Comment by madewild** [comment]
Haha actually you can, I tested on my 27" screen and indeed the map breadcrumb does not disappear anymore so it's good!
