### ISSUE TITLE
Adapt carousel

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#239]
Should we keep the carousel or discard it in the final version?
@gachpas to discuss...

**Comment by gachpas** [comment]
For me we could get rid of it but I think that last time we spoke about it all together, @AThollard said that we keep it for now and we will reconsider for the final version. Anne, i sit correct?

**Comment by AThollard** [comment]
@madewild to discuss together with home page UI for the final version, see issue#242

**Comment by madewild** [comment]
yes, this is also tagged as v1.0 milestone :)

**Comment by madewild** [comment]
Coming back to this, I would suggest keeping a thinner carousel so that the map is not cut in the middle when loading the page...

**Comment by madewild** [comment]
Something like this would be nice (of coursewith better/unstretched picture):

![new_carousel](https://user-images.githubusercontent.com/942488/135602396-53bd51e5-2755-49d9-ae31-47ed42de6f30.png)

**Comment by madewild** [comment]
@raphdom for reference this simulation is with `.carousel-item--img {
              width: 50%;
              height: 20vh;
          }` instead of 35vh

**Comment by madewild** [comment]
@raphdom could we already try a thinner carousel for this release?

**Comment by madewild** [comment]
@raphdom maybe we can use this banner instead to avoid too much stretching
![banner1_v3](https://user-images.githubusercontent.com/942488/146510217-ea000615-cced-481b-abd4-46f966b73f98.jpg)

**Comment by AThollard** [comment]
@slaven777 @Bisiaam are you happy with removing the carousel and just keeping a thinner banner? to be discussed on Thursday 06/12.
Also to be linked with the visuals we want to use for Communication in social media and with Wikimedia.

**Comment by Bisiaam** [comment]
For me I like the idea of the carrousel, it's a great way to start when you don't know a website because it's big and on the top of the page. For us, it's also a great way to promote some information (on a project or on Kohesio itself).
Visually I really like the carousel from cohesion data: https://cohesiondata.ec.europa.eu
<img width="845" alt="image" src="https://user-images.githubusercontent.com/85291854/148028210-9a3dd2f9-162b-4511-a413-13053cbd29fa.png">

It's also automatic and infinite (makes also the website a bit more dynamic I think). I was wondering if we could test it with the pictures we have

**Comment by D063520** [comment]
I think we need something at the beginning. I showed the webpage to some Family and Friends and if you do not tell anything people see it and do not know what to do and what it is about. In my opinion one needs to help the user a bit understanding. Something like "Discover projects financed by the EU across Europe". "Click on the map and see which projects are financed nearby you". Use the search to discover projects about specific topics. Find out who is receiving money from Europen Grants. It's just some ideas ... more to say what I think is missing .....

**Comment by Bisiaam** [comment]
I agree. Maybe next to the map (which is really big), we can have a text to present Kohesio in one sentence and a small text to explain how to use it

**Comment by madewild** [comment]
So the goal now is:
- to have three visuals clearly adrressing three kinds of publics
- to make the carousel rotate automatically
We are waiting for the visuals...

**Comment by raphdom** [comment]
@AThollard when do we get the new images?

**Comment by AThollard** [comment]
@raphdom I've asked REGIO graphic designers, waiting for their input. What would be your deadline to include this in version 1.0?

**Comment by madewild** [comment]
Still this week would be better...

**Comment by gachpas** [comment]
@madewild , FYI, the 3 banners for carrousel were received this pm and have been sent to Alex's team for final validation.  Due date for commenting is this Wednesday.

**Comment by gachpas** [comment]
![Kohesio_webbanner_data enthousiasts-geek](https://user-images.githubusercontent.com/74774446/152116322-adaae578-ff9f-4889-b28e-8e428dc898fd.png)
![Kohesio_webbanner_General public](https://user-images.githubusercontent.com/74774446/152116341-4bddaa85-109d-4b0e-894b-365e5492fe4b.png)
![Kohesio_webbanner_Policy makers-Managing authorities](https://user-images.githubusercontent.com/74774446/152116364-3e137d01-ca32-4414-a843-72be37d63b82.png)

**Comment by gachpas** [comment]
The 3 validated pictures for the carrousel.

**Comment by gachpas** [comment]
and related messages: 
         Curious to discover what Europe does in your region or city? Explore Kohesio map (General public)
         Are you looking for inspiration or successful EU projects to share?  Enjoy the project search advanced functionalities (Policy makers/Managing authorities)
         Do you want to reuse Kohesio open and linked data? Navigate the EU knowledge graph and export datasets (data enthousiasts/geek)
@AThollard , could you please confirm that yo uhave not received any modification after having sent them to the graphic designers and these are indeed the final ones? Thanks

**Comment by madewild** [comment]
Thanks @gachpas 
@omar0z could you please prioritise this task?

**Comment by AThollard** [comment]
I confirm the messages, and the order:
1- Curious to discover what Europe does in your region or city? Explore Kohesio map -> blue banner with the bicycle
2 - Are you looking for inspiration or successful EU projects to share? Enjoy the project search advanced functionalities-> orange banner with the puzzle
3 - Do you want to reuse Kohesio open and linked data? Navigate the EU knowledge graph and export datasets-> violet banner with virtual reality headset

**Comment by omar0z** [comment]
These messages are great! and are a perfect opportunity for a call to action.

I understand that for banner 1 there is no need for it as the users are already on the map, and that the call to action for banner 2 would be "Go to Projects". 

However, for banner 3, where should I send an user that would like to "reuse Kohesio open and linked data"? Where do we export the datasets in the current UI?

**Comment by AThollard** [comment]
Thanks @omar0z . Happy that you like the messages, result of a hard teamwork.
For the call of action: 
Banner 1 no need as indeed this is an implicit one to go to the map
Banner 2: Go to projects: https://dev.kohesio.eu/projects
Banner 3: can we have 2 links? "knowledge graph" linking to "https://linkedopendata.eu/wiki/The_EU_Knowledge_Graph" and "export datasets': https://data.linkedopendata.eu/
Thks

**Comment by madewild** [comment]
Just my 2 cents:

For banner, 1 we could add an anchor at the level of the text "in my region", so if the user clicks on it the page is "scrolled" automatically to the map. Then instead of:
![bad](https://user-images.githubusercontent.com/942488/152163833-cb309a5b-500d-4678-93e6-7d6834caa854.png)
the user sees immediately:
![good](https://user-images.githubusercontent.com/942488/152163884-aa4bc561-1041-43f6-b8d8-9e5d3d3912af.png)
It also has the advantage that something is happening for all 3 banners, else people will wonder if there is a bug with the first.

For banner 3, the second link will become https://kohesio.ec.europa.eu/data (@raphdom can you confirm we will use this instead of https://data.kohesio.ec.europa.eu ?). I don't know about using two links, maybe it can be confusing... To discuss.

**Comment by madewild** [comment]
Perfect for me, except that the KG URL is https://linkedopendata.eu (or https://knowledgegraph.eu) ;)

**Comment by roberto-musmeci** [comment]
I think banner 3 should be linked to a page where it is clearly explained we provide two main services: 
- querying the KG (SPARQL end point) 
- downloading csv files

I don't know if a page like this exists already or if we can readapt one.

**Comment by omar0z** [comment]
Thank you all!

@roberto-musmeci:  it is an interesting proposal, however I have been instructed to keep the site map as it is now for the v1.0 launch. Moreover, implementing a fully functional SPARQL client inside Kohesio before the v1.0 launch is quite ambitious in my view, considering all other pending tasks.  

@madewild: Great idea! I'll set the anchor up.

@AThollard: Considering that most of the target audience is interested in the data, What about if banner 3 includes a download button as the call to action? I will move forward with this approach to keep development going, but your input is always appreciated.

**Comment by madewild** [comment]
@omar0z we have already the sparql endpoint ;) it would be a matter of presenting the options to a specialised audience... we can discuss during the coordination meeting on Friday

**Comment by AThollard** [comment]
Let's discuss on Friday. One option could be to re-organise the existing https://knowledgegraph.eu page, separating clearly the Kohesio related 'services': export and query  (for now everything is a bit mixed up).
Not for version 1.0 in any case.

**Comment by madewild** [comment]
A first version of the new carousel is available on https://dev.kohesio.eu/ :)
To discuss tomorrow...

**Comment by madewild** [comment]
@omar0z the carousel height is much bigger again, compare with https://kohesio.eu/ ... did you change something? I would prefer to keep it slim, especially since we will have to add the Europa header as well.

**Comment by madewild** [comment]
PS to @AThollard and colleagues, the auto-rotating of the carousel is not yet ready and will probably be for 1.1

**Comment by AThollard** [comment]
Really nice! 
Let's discuss tomorrow for the details (don't worry not about the colors ;-)

**Comment by omar0z** [comment]
@madewild nope, the only changes have been 1) adding the text and the images, and 2) editing the css of the images inside the carousel to keep their aspect ratio

**Comment by madewild** [comment]
OK then maybe the images do not have the expected ratio... we'll discuss if we crop them or leave as is.

**Comment by madewild** [comment]
Here's a proposal with the white space at the top of each image cropped out. Height reduced from 938 to 825 pixels. :)
![kohesio-citizens2](https://user-images.githubusercontent.com/942488/152431468-a7555f3e-31ca-4ce1-8ee0-0504d8213e33.png)
![kohesio-policy2](https://user-images.githubusercontent.com/942488/152431484-97998e1d-a810-421d-9e01-854d309ed124.png)
![kohesio-data2](https://user-images.githubusercontent.com/942488/152431492-c714837b-faba-4b9d-824c-bc9f10d4eb74.png)

**Comment by madewild** [comment]
@omar0z the first part of the carousel has an extra space below, which you can see when you click on the image (orange frame):
![orange_border](https://user-images.githubusercontent.com/942488/152432087-2263e863-387e-4ecd-bf9a-edc050f856d5.png)

**Comment by gachpas** [comment]
speaking about the carousel, do you have th epossibility to have the same kind of carousem that the one used for the countdown page (i.e. the width of the carousel is aligned on the width of th emap and the little arrow (allowing to navigate the carousel) are part of the carousel (and not outside of teh carousel)? I ncase @AThollard , confirms this choice, it could be for another version if too complicated for now....

**Comment by madewild** [comment]
This would be in the scope of #342

**Comment by madewild** [comment]
So summary of changes (in addition to #341 #345 #346):

- [ ] Replace all 3 images with the ones above (keep original filenames, not the ones with "2")
- [ ] Adapt CSS to adjust to the new image ratio
- [ ] Adapt the 3 texts (@AThollard will provide the new versions below)
- [ ] Keep the original case of the messages instead of enforcing full uppercase

**Comment by madewild** [comment]
@AThollard I did some tests with the texts on https://dev.kohesio.eu/ but feel free to suggest changes...

**Comment by madewild** [comment]
I discussed with Anne and the texts are good enough for now so closing. :)
