### ISSUE TITLE
Add polygons for regions on homepage map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#24]
Waiting to know NUTS level needed for each country
geoJSON data available on https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts

**Comment by madewild** [comment]
Also, which scale should we use?

**Comment by madewild** [comment]
For homepage

**Comment by D063520** [comment]
is this not the same as the map without filters? I changed the scale that I send you via API, it should be light-way enough to take it from the API

**Comment by raphdom** [comment]
done
