### ISSUE TITLE
Harmonise font size

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#240]
The fonts are not aligned anymore (size and font)
e.g.https://kohesio.eu/projects/Q140362
![12-07-2021_154751](https://user-images.githubusercontent.com/74774446/125298570-8dac2c00-e328-11eb-80db-f96562058474.jpg)

**Comment by madewild** [comment]
I think the font is the same everywhere, but the size should be harmonised.

**Comment by raphdom** [comment]
this should be good, @madewild can you check and close it, please?

**Comment by madewild** [comment]
Looks good to me although it's small...
@gachpas can you test on dev (e.g. https://dev.kohesio.eu/projects/Q139379) and provide feedback? Now it's 12px everywhere, but we could also put 14px everywhere if better.

**Comment by raphdom** [comment]
ok, now is better with relative sizes. @madewild

**Comment by gachpas** [comment]
Thanks @raphdom ;)

**Comment by madewild** [comment]
Perfect, thank you both!
