### ISSUE TITLE
loosing navigation when going back

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#249]
It is also a point that we have already discussed: when selecting some sorting (for instance in the beneficiaries list), then applying some filtering, I arrive to a list that I want to consult. However, if I open a project and go back, I have lost my selection, which is not at all user friendly.

**Comment by madewild** [comment]
You should use the "back" button of the browser and not the breadcrumb, and the filters are kept.
@gachpas can you confirm it works?

**Comment by gachpas** [comment]
Hello @madewild , it works on laptop but not on mobile.

**Comment by madewild** [comment]
@raphdom anything we can do on mobile?

**Comment by raphdom** [comment]
So, the problem here is not the mobile, the sort feature is not persisted even on desktop, the filters are but the sort non. @madewild maybe we can close this issue and open another one to persist the sort in projects and beneficiaries list.

**Comment by madewild** [comment]
@gachpas could you clarify what you mean by "I have lost my selection"? you mean the filters or the sorting order? is the behaviour diffrent on desktop and mobile?

**Comment by raphdom** [comment]
@madewild and @gachpas. Now the sort is persisted, even if you refresh the page or use the back button from the detail page you will not lose the sort anymore.

**Comment by madewild** [comment]
Great! @gachpas can you confirm the issue is solved now?

**Comment by gachpas** [comment]
@madewild, great! It works ;)

**Comment by madewild** [comment]
perfect, closing
