### ISSUE TITLE
Update search help

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#254]
Add semantic search explanations (quotes for strict search without semantic expansion)

**Comment by raphdom** [comment]
@madewild need more info here

**Comment by madewild** [comment]
Waiting to see if we integrate the semantic search now or later, we need to sync both issues...

**Comment by madewild** [comment]
Implemented in dev: https://dev.kohesio.eu/projects
@AlyHdr and @svili could you go to this page, click on the "i" next to keywords and review what I wrote to make sure it's in line with reality of the (semantic) search?

**Comment by svili** [comment]
Looks good to me!

**Comment by madewild** [comment]
Added the use of explicit AND, closing now.
