### ISSUE TITLE
Show expanded keywords from semantic search

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#255]
First wait for @svili to expose them

**Comment by raphdom** [comment]
@svili it is already exposed? We can work on that?

**Comment by svili** [comment]
> @svili it is already exposed? We can work on that?

Yes, if you use the dev version @ http://kohesio-search-dev.eu-west-1.elasticbeanstalk.com/docs#/default/search_search_get

**Comment by madewild** [comment]
@raphdom you have to wait for @D063520 and @AlyHdr to integrate in the backend
I will organise a meeting on this tomorrow

**Comment by D063520** [comment]
It is done, can you check? ... we pass it directly to the description, so it is already rendered. there is nothing really to do except to try it ....

**Comment by madewild** [comment]
@AlyHdr so can you also send a list of 10 expanded keywords?

**Comment by AlyHdr** [comment]
<img width="673" alt="Screenshot 2021-09-23 at 15 00 41" src="https://user-images.githubusercontent.com/43681203/134511269-b7f64513-dbe1-4727-896a-6552b3b2c333.png">

@madewild the search is now over 10 expanded keywords, and the API returns a list of keywords @raphdom

**Comment by raphdom** [comment]
@AlyHdr thank you, it is implemented on dev:
![image](https://user-images.githubusercontent.com/5124917/134516803-9f4a09de-6144-4716-a18c-057a086efacb.png)

**Comment by AlyHdr** [comment]
Coool!

**Comment by madewild** [comment]
We have again a font size mismatch here... For me:
- "Also matching..." is 12.8px
- the keywords are 12px
- "Use my keyword only" is 14px

Can we use the same (relative) size everywhere?
Also, can we save space by putting the button "Use my keyword only" next to "Also matching..." ?

**Comment by madewild** [comment]
Since we can now use multiple words with semantic search, should be "Use my keyword**s** only"

**Comment by raphdom** [comment]
The font-size is already relative and it is normal have a smaller size just to differentiate because this is part of the field above., about to put the "Also matching..." in the same line as "Use my keywords only", the only way to not pollute the space is like that:
![image](https://user-images.githubusercontent.com/5124917/134859784-0ea9878d-f12e-4587-8926-1461f6cf04c0.png)

**Comment by madewild** [comment]
Maybe we can put just "Also matching:" to have something shorted and on one line. Can you try?

**Comment by raphdom** [comment]
![image](https://user-images.githubusercontent.com/5124917/134860327-37f915ad-2adc-469d-a1db-8c6e4e4f275f.png)
like this?

**Comment by madewild** [comment]
For me it's fine, I would just put the same small font size for "Use my keywords only" if possible.

**Comment by raphdom** [comment]
fixed, @madewild can you check and close the issue, please?
