### ISSUE TITLE
Show multiple intervention fields and thematic objectives

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#256]
Can be more than one (like beneficiaries)
interest of @roberto-musmeci

**Comment by madewild** [comment]
3000 projects have multiple intervention fields: https://query.linkedopendata.eu/#select%20DISTINCT%20%3Fproject%20where%20%7B%0A%20%20%20%20%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ9934%3E%20.%0A%20%20%20%20%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP32%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ25%3E%20.%0A%20%20%20%20%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP888%3E%20%3Fcoi1%20.%0A%20%20%20%20%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP888%3E%20%3Fcoi2%20.%0A%20%20%20%20FILTER%20%28%3Fcoi1%20%21%3D%20%3Fcoi2%29%0A%7D

for instance https://linkedopendata.eu/wiki/Item:Q9779 has two (056 and 064)

waiting for https://github.com/ec-doris/kohesio-backend/issues/85 so postponed

**Comment by madewild** [comment]
2000+ have multiple TO
https://query.linkedopendata.eu/#select%20DISTINCT%20%3Fproject%20where%20%7B%0A%20%20%20%20%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ9934%3E%20.%0A%20%20%20%20%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP32%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ25%3E%20.%0A%20%20%20%20%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP888%3E%20%3Fcoi1%20.%0A%20%20%20%20%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP888%3E%20%3Fcoi2%20.%0A%20%20%20%20FILTER%20%28%3Fcoi1%20%21%3D%20%3Fcoi2%29%0A%20%20%20%20%3Fcoi1%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1848%3E%20%3Fto1%20.%20%0A%20%20%20%20%3Fcoi2%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1848%3E%20%3Fto2%20.%20%0A%20%20%20%20FILTER%20%28%3Fto1%20%21%3D%20%3Fto2%29%0A%7D

for instance https://linkedopendata.eu/wiki/Item:Q68696 has  2 intervention fields : 
- https://linkedopendata.eu/wiki/Item:Q200692 part of TO https://linkedopendata.eu/wiki/Item:Q236697
- https://linkedopendata.eu/wiki/Item:Q200691 part of TO https://linkedopendata.eu/wiki/Item:Q236698

**Comment by madewild** [comment]
the backend has been changed, ready for you @raphdom

**Comment by madewild** [comment]
@raphdom moving to this release because there is a breaking change in the api...

**Comment by madewild** [comment]
When implemented it should also fix ec-doris/kohesio-data-import#173

**Comment by raphdom** [comment]
fixed on dev, can you check please?

**Comment by madewild** [comment]
I would remove the bullet points (dashes)...

**Comment by madewild** [comment]
Here's an example to test: https://dev.kohesio.eu/projects/Q68696

**Comment by roberto-musmeci** [comment]
Also, what do you think about displaying the code too ?

**Comment by madewild** [comment]
I think we decided not to because too technical for common users... to check with @AThollard

**Comment by madewild** [comment]
we don't have this code in the api right now (only the one of TO) so we leave like this for this release
@raphdom so we just need to remove the bullet points...

**Comment by madewild** [comment]
we just need a small padding between categories etc. thx

**Comment by raphdom** [comment]
you can test on dev. padding was added.

**Comment by madewild** [comment]
sorry @raphdom to bother you but I find it hard to see the padding with the big line-height... I would go for something like this:
![padding](https://user-images.githubusercontent.com/942488/146057596-400f6b55-2109-4990-b177-7e045226ccad.png)

(padding 3px instead of 2px and line-height 1.4 instead of 1.6)

**Comment by raphdom** [comment]
done, can you test on dev please?

**Comment by madewild** [comment]
excellent, thx

**Comment by AThollard** [comment]
Fine with me.
