### ISSUE TITLE
Replace EU contrib by total budget

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#257]
In project list
Already available in API
Change amount + label ("Total budget")

**Comment by raphdom** [comment]
Change from "EU contribution" to "Total budget"? And what about the sort and the filter that we have in this field. IT will be weird have a sort and a filter in one of the fields that doesn't appear in the list. Maybe we should change as well but not sure if we support this in the API.

**Comment by madewild** [comment]
Good point, we should adapt the filter and sort as well. @D063520 is this supported by the API? If not we can postpone to next version...

**Comment by D063520** [comment]
this is already possible, the parameter is called "orderTotalBudget" and not "orderTotalBudget". Can you check if it is this what you want?

**Comment by raphdom** [comment]
@madewild 
it is okay like that?

![image](https://user-images.githubusercontent.com/5124917/134889050-b4de12c1-ccf6-4797-bbcd-6d659ea2a009.png)

**Comment by raphdom** [comment]
and I will leave the EU contribution filter

**Comment by madewild** [comment]
OK for me!

**Comment by raphdom** [comment]
fixed @madewild

**Comment by madewild** [comment]
I had a timeout from the API with the filter, but now seems fixed with the cache... will see if it happens again.
https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/project?offset=0&limit=15&budgetSmallerThan=1000000000&budgetBiggerThan=100000000&orderTotalBudget=false
FYI @D063520
