### ISSUE TITLE
Create a "Terms of use" page

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#260]
Directly linked-> create a related "Term of use" page for copyrights on the EC logo, maps, what is under creative commons etc...)

_Originally posted by @AThollard in https://github.com/ec-doris/kohesio-data-import/issues/139#issuecomment-877085895_

**Comment by madewild** [comment]
Linked to #261 and #298

**Comment by madewild** [comment]
@roberto-musmeci @AThollard is this still in the scope for 1.0 or to be postponed? we would need the text asap...

**Comment by roberto-musmeci** [comment]
I think we are covered by the standard legal notice of the EU Commission (e.g. https://ec.europa.eu/info/legal-notice_en#copyright-notice). I will discuss it with @AThollard today

**Comment by AThollard** [comment]
@madewild @roberto-musmeci we are covered indeed by the legal notice in the footer. Not clear to me if we are going to have the DG COM template with the footer already in place for version 1.0?
I think you can close this issue.

**Comment by madewild** [comment]
No, ECL integration is for 1.1: #302 
Closing then
