### ISSUE TITLE
Hide co-financing rate when n/a or zero

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#263]
https://dev.kohesio.eu/projects/Q3060553

Funded by EU: n/a (0%)

should be

Funded by EU: n/a

**Comment by raphdom** [comment]
fixed, @madewild can you check and close the issue, please?

**Comment by madewild** [comment]
Sorry @raphdom other case: https://dev.kohesio.eu/projects/Q86132
Here the total budget is n/a so the co-financing rate should also be hidden.

Funded by EU: 148 147 400,56 € (0%)

should be

Funded by EU: 148 147 400,56 €

**Comment by raphdom** [comment]
fixed, @madewild can you check, please?

**Comment by madewild** [comment]
Looks good.
