### ISSUE TITLE
Show name of country when hovering over flag

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#264]
Both on https://dev.kohesio.eu/beneficiaries and https://dev.kohesio.eu/beneficiaries/Q3064623
If you don't know the flag it's tricky to guess the country... If the country name is available in the API we could show it in a tooltip when hovering with the mouse over the flag (or at least the country code).

**Comment by AThollard** [comment]
Ideally the country name (but then come the multilinguism question), so rater the country code (not sure it's clearer?)
Can we discuss this with @slaven777 @Bisiaam  on Friday as they have more experience with Member states preferences?

**Comment by AThollard** [comment]
but in any case I agree the flag itself is not very clear

**Comment by madewild** [comment]
I propose to postpone for now as time is short

**Comment by madewild** [comment]
@D063520 could you add a countryName field to https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/beneficiaries?offset=0&limit=15 ? and also to https://dev.kohesio.linkedopendata.eu/api/facet/eu/beneficiary?id=https://linkedopendata.eu/entity/Q3064623
Thanks

**Comment by svili** [comment]
Added a tooltip for this in the right places. If the countryName is not available it falls back to the countryCode.
![image](https://user-images.githubusercontent.com/11196689/151008339-d18801ad-ce16-49bb-a8c8-fcac7cbb4594.png)

**Comment by madewild** [comment]
OK tested and approved on both https://dev.kohesio.eu/beneficiaries and https://github.com/ec-doris/kohesio.eu/issues/264
So @AThollard  for now we display the country code but if we localize the website later we could add the country name in the local language of the user.

**Comment by Bisiaam** [comment]
For Greece should we use GR or EL ? 
https://publications.europa.eu/code/pdf/370000en.htm

**Comment by madewild** [comment]
"The abbreviations to use are the ISO codes, except for Greece, for which EL is recommended (instead of GR)."

Did not know that... should we change everywhere at some point then?

**Comment by Bisiaam** [comment]
I guess so

**Comment by madewild** [comment]
Moved to a separate issue since this one is closed.
