### ISSUE TITLE
Rendering breakdown by funds

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio.eu#265]
Is it normal ? 

https://dev.kohesio.eu/beneficiaries/Q3113578

![image](https://user-images.githubusercontent.com/86654885/134889557-899a035c-c913-488d-b1d0-68eb2165181b.png)

**Comment by madewild** [comment]
Oops, @raphdom I think you introduced a bug here ;)

**Comment by raphdom** [comment]
my bad, colateral effect :) now is fixed @madewild

**Comment by madewild** [comment]
much better ;)
