### ISSUE TITLE
Display several markers on the map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#268]
Some projects have multiple locations, e.g. https://dev.kohesio.eu/projects/Q86132
The API returns several points in "coordinates" but the UI only shows one, we should display all.
https://github.com/ec-doris/kohesio-backend/issues/77 will also return all geoJSON

**Comment by madewild** [comment]
All locations (and related NUTS) can be seen on https://linkedopendata.eu/wiki/Item:Q86132

**Comment by madewild** [comment]
The multiple polygons are ready but you need to sync with @AlyHdr because there is a breaking change in the API...

**Comment by raphdom** [comment]
notice there are several points duplicated in the API when we have more than one coordinate.
![image](https://user-images.githubusercontent.com/5124917/135214180-e80078b2-c217-4d0f-b1d0-5654e5c8c057.png)
I am drawing the several points already.
![image](https://user-images.githubusercontent.com/5124917/135214248-29455bde-93c9-4a7d-932b-ae5ee2d75852.png)
Question: We are going to receive more than one geoJson?
@AlyHdr and @madewild

**Comment by madewild** [comment]
Yes, Ali provided the multiple geoJSON yesterday but this broke the API so he reverted the change...
As soon as he's available you can sync with him to deploy both the fix in the API and the change in the UI.
See https://github.com/ec-doris/kohesio-backend/issues/77 so you can know what to expect and anticipate already: "The API returns a list of geoJson and the coordinates, the label is now "regionText": "In multiple locations, Poland"."

@AlyHdr could you maybe also deduplicate the points in the api?

**Comment by AlyHdr** [comment]
Yes all those fixes were introduced yesterday but I reverted them because the UI broke, I will deploy again the latest changes you can check here:

https://github.com/ec-doris/kohesio-backend/issues/77

**Comment by AlyHdr** [comment]
> notice there are several points duplicated in the API when we have more than one coordinate. ![image](https://user-images.githubusercontent.com/5124917/135214180-e80078b2-c217-4d0f-b1d0-5654e5c8c057.png) I am drawing the several points already. ![image](https://user-images.githubusercontent.com/5124917/135214248-29455bde-93c9-4a7d-932b-ae5ee2d75852.png) Question: We are going to receive more than one geoJson? @AlyHdr and @madewild

Yes @raphdom the API returns a list of geoJson and the duplicates are not there anymore.

**Comment by raphdom** [comment]
okay, I already did and deploy a change to handle multiple geoJson's... maybe should be fine in the ui side.

**Comment by raphdom** [comment]
it is fixed @AlyHdr and @madewild

**Comment by madewild** [comment]
Mostly good except that the initial zoom is now wrong on https://dev.kohesio.eu/projects/Q86132

**Comment by madewild** [comment]
![wrong_zoom](https://user-images.githubusercontent.com/942488/135233695-146b9ce1-a6dc-49e8-8472-02f2aa532d39.png)

(also double "in" mentioned to Ali in https://github.com/ec-doris/kohesio-backend/issues/77)

**Comment by raphdom** [comment]
the zoom is based on the last region rendered. Not easy to calculate the boundaries with multiple regions in the map. Maybe we could fixed this issue and create a new one to evaluate if I can do it with leaflet. Another solution is if @AlyHdr is able to send me the geoJson combined of all regions that I can centralize the map.

**Comment by madewild** [comment]
Mmmh, so a big MultiPolygon combining everything... @AlyHdr is this easily feasible? If not I create a separate issue and keep for next release.

**Comment by AlyHdr** [comment]
Mmm I would suggest to try to fit the bounds with leaflet based on the coordinates, I already did this in some projects but maybe here it's different. 
something like:
```
var group = new L.featureGroup([marker1, marker2, marker3]);

map.fitBounds(group.getBounds());
```
If this doesn't work I'm not sure how we could do it because I think the geometries are based on the nuts and I think it wouldn't be easy to find the nuts that combines all the found nuts of each coordinate, especially that it could be that they don't rely under the same upper nuts region.

**Comment by madewild** [comment]
Moved to separate issue
