### ISSUE TITLE
Correct initial zoom when multiple locations

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#270]
Mmm I would suggest to try to fit the bounds with leaflet based on the coordinates, I already did this in some projects but maybe here it's different. 
something like:
```
var group = new L.featureGroup([marker1, marker2, marker3]);

map.fitBounds(group.getBounds());
```
If this doesn't work I'm not sure how we could do it because I think the geometries are based on the nuts and I think it wouldn't be easy to find the nuts that combines all the found nuts of each coordinate, especially that it could be that they don't rely under the same upper nuts region.

_Originally posted by @AlyHdr in https://github.com/ec-doris/kohesio.eu/issues/268#issuecomment-929971146_

**Comment by madewild** [comment]
See https://dev.kohesio.eu/projects/Q86132

**Comment by madewild** [comment]
Much better!
![new_zoom](https://user-images.githubusercontent.com/942488/135238808-df943224-1e88-4fe4-a7c1-d2755630ff35.png)

@AThollard @roberto-musmeci does it seem OK that the NUTS polygon is truncated at the top? if not we can always try to improve later...

**Comment by madewild** [comment]
Oops @raphdom side effect is that other projects with one location like https://dev.kohesio.eu/projects/Q2659969 are zoomed too much now! :(

**Comment by madewild** [comment]
Another cleaner option would be to parse all geometries and keep the smaller and bigger values for latitude and longitude, no? Probably better to do it in the API though @AlyHdr ...

**Comment by AlyHdr** [comment]
> Much better! ![new_zoom](https://user-images.githubusercontent.com/942488/135238808-df943224-1e88-4fe4-a7c1-d2755630ff35.png)
> 
> @AThollard @roberto-musmeci does it seem OK that the NUTS polygon is truncated at the top? if not we can always try to improve later...

Yes this behaviour is expected, for one coordinate projects can't we just fit the bounds based on the polygon as before and otherwise just like this?

**Comment by roberto-musmeci** [comment]
> Much better! ![new_zoom](https://user-images.githubusercontent.com/942488/135238808-df943224-1e88-4fe4-a7c1-d2755630ff35.png)
> 
> @AThollard @roberto-musmeci does it seem OK that the NUTS polygon is truncated at the top? if not we can always try to improve later...

Yes, it is indeed much better and representative of to reality the project ! :) 

If possible, it would be good to zoom out a bit to see the boundaries of all the regions involved. 
Usually, these projects are infrastrutture projects and a lot of clicks because they have very big budget. 
Up to you for the planning for that.

**Comment by madewild** [comment]
https://leafletjs.com/reference-1.7.1.html#map-fitbounds should do the trick :)

**Comment by raphdom** [comment]
Deploying this right now with this behavior. 5min and you can test it

**Comment by raphdom** [comment]
done, you can test it @madewild @AlyHdr @roberto-musmeci

**Comment by madewild** [comment]
Working perfectly both on single-location (https://dev.kohesio.eu/projects/Q2659969) and multiple-location (https://dev.kohesio.eu/projects/Q86132) projects, awesome!!
