### ISSUE TITLE
Hide Project website and Programme website if n/a

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#278]
Before:
![web_before](https://user-images.githubusercontent.com/942488/144610605-9350a1c2-bf77-46ce-b0f4-3e13d44fca8f.png)

After:
![web_after](https://user-images.githubusercontent.com/942488/144610624-bbf6173a-7ba4-4323-925e-94fa5a6fc939.png)

**Comment by raphdom** [comment]
fix, can you check in dev, please?

**Comment by madewild** [comment]
indeed good on https://dev.kohesio.eu/projects/Q2660753
