### ISSUE TITLE
tiles are very slow at rendering with new map

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#280]
I like the new map, but I feel that when zooming in it takes longer until the tiles are loaded. In particular it is difficult to find cities. This is the result after a while ....
<img width="1680" alt="Screenshot 2021-12-13 at 11 07 25" src="https://user-images.githubusercontent.com/10883585/145792631-8e73b223-b7e6-485a-86ca-d48df66326d0.png">

**Comment by madewild** [comment]
cannot reproduce on my side, it's fully loaded in less than a second:
![tiles](https://user-images.githubusercontent.com/942488/145793055-be9b7629-d8bb-48c7-8c7a-31991dc46497.png)

**Comment by madewild** [comment]
@D063520 can you try again to see if it's still happening?
anyone else experiencing issues with map background loading time?

**Comment by D063520** [comment]
looks better
