### ISSUE TITLE
Privacy statement

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#281]
I think we need:
a) a pop-up warning users with a link to 
b) a dedicated section on data protection (e.g : https://webgate.ec.europa.eu/regiokm/display/ST/6.+Data+protection+for+RegioWiki)
@gachpas to include in our lists as a priority under the GDPR actions (also consult the DPC and finalise the record for GDPR to the DPO)
Sorry for the acronyms: GDPR: General data protection regulation, DPC (data protection correspondent, DPO: Data protection officer

_Originally posted by @AThollard in https://github.com/ec-doris/kohesio-ui/issues/247#issuecomment-982795679_

**Comment by AThollard** [comment]
Hi @madewild , could you please confirm that we don't use geolocation info anymore for the 'project near me' feature.
And so basically at this stage we do not use or process personal data at all in Kohesio.

**Comment by D063520** [comment]
Hi, so we use the IP to infer the geo location. But we do not store this piece of information anywhere. In this sense we do not store personal information.

**Comment by AThollard** [comment]
Thanks @D063520 , we will double check with our data protection correspondent to be sure.

**Comment by madewild** [comment]
Relevant Europa docs:

- https://ec.europa.eu/info/cookies_en
- https://ec.europa.eu/info/legal-notice_en
- https://ec.europa.eu/info/privacy-policy_en

**Comment by madewild** [comment]
@AThollard same question here, is there something to do for this release?

**Comment by AThollard** [comment]
@madewild we are trying to push to have the standard footer with the legal requirements requested by DG COM
"Legal requirements:
All legal requirements applicable to European Commission websites must be respected, in particular in relation to:
· the obligations concerning the protection of personal data 
· web content accessibility guidelines
· no use of [third-party tools](https://wikis.ec.europa.eu/display/WEBGUIDE/04.+Third-party+vs.+corporate+tools+and+services)
· copyright/ intellectual property rights
· use of [cookies](https://wikis.ec.europa.eu/display/WEBGUIDE/04.+Cookies) 
Note that the corporate service Cookie Consent Kit must be implemented on all pages of the website."
Still in discussion but I will try to have a decision today.

**Comment by AThollard** [comment]
Please push this to version 1.1 and link it to ECL look and feel

**Comment by madewild** [comment]
Linked to #302

**Comment by madewild** [comment]
@AThollard for inspiration you can check https://digital-strategy.ec.europa.eu/en which has its own privacy statement (and copyright notice) in the footer on top of the standard privacy policy and legal notice included in any Europa website

**Comment by AThollard** [comment]
@gachpas could you please communicate the updated privacy statement document as discussed with Maria so @madewild can create a specific page?
We can then link the 'privacy statement' in the footer to this page.
Thanks a lot

**Comment by madewild** [comment]
I received it by email, thanks. I suggest to put this on /privacy (link already in the footer), ok for you?

**Comment by AThollard** [comment]
Yes perfect

**Comment by madewild** [comment]
@prototorpedo or @raphdom can you prepare a skeleton of /privacy page? then I will convert the Word document to HTML and add the contents to the page

**Comment by madewild** [comment]
(on the model of the about page)

**Comment by madewild** [comment]
@raphdom created the page, I will add the contents

**Comment by gachpas** [comment]
@madewild , on recommendation of our DPO, we have registered the PS in ARES but I suppose it does not affect what we do with the doc in Kohesio.

Just for alignement purposes the word 'Model' in the titile on the first page of the doc has been removed in the version published on ARES.
Br, PAscal

**Comment by madewild** [comment]
Indeed, this is a separate administrative process.
Here's the working version of the PS: https://kohesio.development.ec.europa.eu/privacy
I will add the other sections today, then I will request the help of @raphdom to have a nice table of contents like on https://digital-strategy.ec.europa.eu/en/pages/legal-notice

**Comment by madewild** [comment]
All sections added, just missing the ToC now. @gachpas can you proofread it?

**Comment by gachpas** [comment]
Hello @madewild , I will do that tomorrow ( I am on the testing right now ;))
Also, I have spoken with Alain Vanden Borre and I will have to pass through different pages to align teh contact details, ...
Br,
Pascal

**Comment by madewild** [comment]
Great, for that you can refer to #368

**Comment by madewild** [comment]
In the end I managed to implement the inpage navigation myself. :)
@gachpas you can test on https://kohesio.development.ec.europa.eu/privacy and close if all is fine

**Comment by madewild** [comment]
- [ ] Check inpage nav on mobile

**Comment by madewild** [comment]
@raphdom can you take care of the mobile navigation? too complex for me ;)

Other nice to have: https://digital-strategy.ec.europa.eu/en/pages/legal-notice#ecl-inpage-km0gfb8o has this nice autofocus on the correct section when you scroll...

![inline_focus](https://user-images.githubusercontent.com/942488/154571226-8959d5dc-4629-4584-81b5-7ae5d9c2aea3.png)

**Comment by raphdom** [comment]
done, now it works on mobile as expected...
