### ISSUE TITLE
Improve themes

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#283]
I cannot set both the policy objective and the themes filter
<img width="1680" alt="Screenshot 2021-12-16 at 15 54 01" src="https://user-images.githubusercontent.com/10883585/146394611-b3dafe2c-c80b-44e4-a346-1a3fbd4a87b7.png">

**Comment by madewild** [comment]
Indeed there is something wrong with these 2 filters... @raphdom is there a quick fix?

**Comment by raphdom** [comment]
It is explicit like this in the code:
<img width="275" alt="Screenshot 2021-12-17 at 08 54 39" src="https://user-images.githubusercontent.com/5124917/146509450-f0fe9804-ae7f-4075-86d5-d8ccb016464d.png">
It is there for some reason, maybe we don't remember why.

**Comment by madewild** [comment]
OK, to discuss with @AThollard in January then...

**Comment by AThollard** [comment]
If I remember correctly there is a hierarchy between the PO and the TO, for example PO "Green and carbon free Europe" contains 3 Themes: Low carbon economy, climate change, environment protection.
So it should not be exclusive but the PO should filter the related Themes. I think it was implemented in the KG  but let's check together.

**Comment by D063520** [comment]
Hi, it is slightly different .... the intervention field is attached both to a "Policy Objective" and a "Thematic Objective". Here an example:

https://linkedopendata.eu/wiki/Item:Q200734

So basically based on the intervention field we assign projects to a PO or a TO.

**Comment by madewild** [comment]
Strange, I remember like Anne...

**Comment by AThollard** [comment]
On this one I really have my doubts. I am pretty sure that it was not exclusive...maybe we mixed-up with the selection we've made for the home page?

**Comment by AThollard** [comment]
After discussing with colleagues, we suggest the following:
Selecting a PO should filter the related TOs, and vice versa.
Groups of TOs by PO below (thanks @Bisiaam )

**- Smart   Europe**
Research &   Innovation
Information   & Communication Technologies
SME   Competitiveness

  **Green and Carbon free Europe**
Low-Carbon   Economy
Climate Change   Adaptation & Risk Prevention
Environment   Protection & Resource Efficiency
 
**Social Europe**
Sustainable   & Quality Employment
Social   Inclusion & Combating Poverty
Education   & Training
  
**Connected Europe**
 Transport   & Energy Networks
  
**Europe closer to citizen**
 Efficient   Public Administration
  
**Technical Assistance**
 Technical   Assistance

**Comment by madewild** [comment]
Thank you @AThollard 
@raphdom do you foresee a problem to implement this?

**Comment by madewild** [comment]
@AThollard check the alignment with colors on https://dev.kohesio.eu/themes

**Comment by AThollard** [comment]
Hi @madewild, the colors are aligned but not the titles
https://cohesiondata.ec.europa.eu/themes

Colors are not consistent with the PO/TO repartition but we give priority to the consistency among platforms.

Is it difficult to change the TO labels at this stage? Impact on the filters as well.
If yes can be done for milestones 1.2
- SME competitiveness -> Competitiveness of SMEs
- Transport & Energy Networks ->Network Infrastructure in Transport and Energy
- Social Inclusion & Combating poverty -> Social Inclusion
- Education & Training -> Educational and Vocational training.
We plan to revamp all the themes towards a more generic Themes<-> Eurovoc approach at a later stage.

**Comment by svili** [comment]
Needs change in the backend.
I can change on the /themes page but the Theme selector is getting its values from this endpoint:
https://dev.kohesio.linkedopendata.eu/api/facet/eu/thematic_objectives

**Comment by D063520** [comment]
@svili @AThollard : you can change the labels in the wikibase. For example here:

https://linkedopendata.eu/wiki/Item:Q236691

this will be reflected across all the application after a refresh of the cache ...

Salut
Dennis

**Comment by madewild** [comment]
I will do the change in the wikibase
@svili will take care of the interaction between filters, and also adapt the /themes page to fetch from the backend

**Comment by madewild** [comment]
@AThollard the new names already appear on the projects fiches thanks to the new live endpoint
e.g. https://dev.kohesio.eu/projects/Q3097484 has "Social Inclusion"

To appear in the dropdown filter on https://dev.kohesio.eu/projects I guess the cache has to be regenerated (@D063520 ?) so tomorrow

**Comment by AThollard** [comment]
Thanks @madewild let's check tomorrow then

**Comment by AThollard** [comment]
@madewild @raphdom @D063520 I don't see the behaviour below implemented in dev? Filters are still exclusive. Is it going to be solved by the cache regeneration or no link btween the issues?


 After discussing with colleagues, we suggest the following: Selecting a PO should filter the related TOs, and vice versa.
> 
> Groups of TOs by PO below (thanks @Bisiaam )
> 
> **Smart Europe** Research & Innovation Information & Communication Technologies SME Competitiveness
> 
> **Green and Carbon free Europe** Low-Carbon Economy Climate Change Adaptation & Risk Prevention Environment Protection & Resource Efficiency
> 
> **Social Europe** Sustainable & Quality Employment Social Inclusion & Combating Poverty Education & Training
> 
> **Connected Europe**  Transport & Energy Networks
> 
> **Europe closer to citizen**  Efficient Public Administration
> 
> **Technical Assistance**  Technical Assistance

**Comment by madewild** [comment]
see my comment above: "@svili will take care of the interaction between filters" ;)
not done yet ;)

**Comment by AThollard** [comment]
Sorry I read too fast @svili takes care...(just skipped the will)

**Comment by madewild** [comment]
> Thanks @madewild let's check tomorrow then

Can you check now on https://dev.kohesio.eu/projects? Not the interaction yet, but the names have been changes, e.g. https://dev.kohesio.eu/projects?theme=Competitiveness-of-SMEs&sort=Total-Budget-(descending)

@AThollard do you think we should add "Technical Assistance" to https://dev.kohesio.eu/themes to be aligned with the filter? The logo it's already available on https://dev.kohesio.eu/assets/images/topics/TO12.png so it's a quick win.

**Comment by AThollard** [comment]
Thanks, a very small typo (our fault) -> Information and Communication **Technology** (not technologies)
Perfect for the rest.
And yes we can add the Technical Assistance in the themes, ok for the icon as well

**Comment by madewild** [comment]
Changed on https://linkedopendata.eu/wiki/Item:Q236690 (you could do it yourself in the future if you spot other typos ;)
@svili can you add TA on /themes? it should come from the list in the backend (same as for filter)

**Comment by madewild** [comment]
@DiaZork we see that the TO IDs are not in the api https://dev.kohesio.linkedopendata.eu/api/facet/eu/thematic_objectives
could you add them by querying this property in your sparql query: https://linkedopendata.eu/wiki/Property:P1105 ?
so add TO01 for https://linkedopendata.eu/wiki/Item:Q236689 etc.
it will help Vilmos to improve the /themes page and link with the correct icon, thanks

**Comment by madewild** [comment]
In the meantime, @AThollard @roberto-musmeci you can test the interaction between policies and themes filters on https://dev.kohesio.eu/projects

**Comment by madewild** [comment]
TA has already been added on https://dev.kohesio.eu/themes
@roberto-musmeci @AThollard let us know if the colour is ok ;)

**Comment by madewild** [comment]
We should also harmonise the use of "&" vs "and" in all TOs:
![and](https://user-images.githubusercontent.com/942488/152346977-a7b04dc8-3956-4473-93fa-9f1321416f57.png)

**Comment by AThollard** [comment]
> TA has already been added on https://dev.kohesio.eu/themes @roberto-musmeci @AThollard let us know if the colour is ok ;)

This bureaucratic grey matches perfectly with the content of the TA "theme" (Technical assistance').
You are becoming good at this ;-)

**Comment by DiaZork** [comment]
> @DiaZork we see that the TO IDs are not in the api https://dev.kohesio.linkedopendata.eu/api/facet/eu/thematic_objectives could you add them by querying this property in your sparql query: https://linkedopendata.eu/wiki/Property:P1105 ? so add TO01 for https://linkedopendata.eu/wiki/Item:Q236689 etc. it will help Vilmos to improve the /themes page and link with the correct icon, thanks

It's added

**Comment by roberto-musmeci** [comment]
> In the meantime, @AThollard @roberto-musmeci you can test the interaction between policies and themes filters on https://dev.kohesio.eu/projects


Something strange when applying policy objective and thematic filter. The first result in the screenshot is not relevant.  
Also, if you select as theme ITC we get no result back.. I am a bit confused. 
![image](https://user-images.githubusercontent.com/86654885/152378090-ddc74e09-6bb1-4ab4-954e-ca94239f24e7.png)

**Comment by madewild** [comment]
Looks like a bug, @svili could you have a look?

**Comment by AThollard** [comment]
> > In the meantime, @AThollard @roberto-musmeci you can test the interaction between policies and themes filters on https://dev.kohesio.eu/projects
> 
> Something strange when applying policy objective and thematic filter. The first result in the screenshot is not relevant. Also, if you select as theme ITC we get no result back.. I am a bit confused. ![image](https://user-images.githubusercontent.com/86654885/152378090-ddc74e09-6bb1-4ab4-954e-ca94239f24e7.png)

This project has several TO, one of them being 'Research and innovation'. So it's a bit confusing in the result list but it's logical from a graph perspective no?

**Comment by madewild** [comment]
Ah yes thanks @AThollard, maybe we should display "multiple TOs" in the result list? Actually I mentioned this on https://github.com/ec-doris/kohesio.eu/issues/301#issuecomment-1021899297

**Comment by svili** [comment]
Yes this happens on all themes more or less, I also thought its because of multiple TOs and we use the first one in the TO-list as the theme.

**Comment by AThollard** [comment]
Thanks @svili and sorry for big and small cow lovers, but I think we should get rid of the images and the audiovisual heading for the time being. Or create a serious game: "Cowhesio": find the cow related projects :-D
Ok sorry, let's discuss tomorrow.

**Comment by madewild** [comment]
I have changed "and" to "&" (ampersand) in https://linkedopendata.eu/wiki/Item:Q236695 and https://linkedopendata.eu/wiki/Item:Q236698 in the Wikibase, will be visible tomorrow on dev.

Interaction between PO and TO filters is back.

For the multiple TO issue, see #350.
