### ISSUE TITLE
Add placeholder text for some filters

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#284]
the region tab is empty is not country is selected. It can be confusing. Maybe we can write ("select country first")

**Comment by madewild** [comment]
or hide the region filter if no country selected?

**Comment by madewild** [comment]
also hide programme filter (in advanced) if country not selected

**Comment by madewild** [comment]
Add placeholder text

**Comment by madewild** [comment]
"Select country first" should be the default text for both filters.

**Comment by svili** [comment]
Unfortunately in the eUI component library the placeholder doesn't work if the selector options are empty.
So this is the best I could do:
- If there is no country selected add "select country first" to the label + disable the selector
- When a country is selected activate the selector and remove the addition of the label text
![image](https://user-images.githubusercontent.com/11196689/150820013-2b97fb57-91f2-4464-bb8a-ae2a77c25ca0.png)

**Comment by madewild** [comment]
@roberto-musmeci @athollard does this seem acceptable?

**Comment by roberto-musmeci** [comment]
Good for me

**Comment by madewild** [comment]
I tested on https://dev.kohesio.eu/projects, working for the region filter but I'm noticing the same behaviour described on https://github.com/ec-doris/kohesio.eu/issues/303 : nothing in the Programme filter even when one country is selected. @svili can you check?

**Comment by madewild** [comment]
Actually the programs are not provided by the backend: https://dev.kohesio.linkedopendata.eu/api/facet/eu/programs?country=https://linkedopendata.eu/entity/Q16

it works in prod: https://kohesio.linkedopendata.eu/api/facet/eu/programs?country=https://linkedopendata.eu/entity/Q16

@DiaZork @D063520 could you fix this?

**Comment by DiaZork** [comment]
It's fixed now

**Comment by D063520** [comment]
ahaha .. I was also on it and it just worked! Thank you Jonathan!

**Comment by madewild** [comment]
Perfect!
