### ISSUE TITLE
putting loader in beneficiary page

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#289]
Some search requests are slow, because we have a lot of beneficiaries, I suggest putting a loader as in the project page

**Comment by madewild** [comment]
Why not, but why is it faster for projects although we have many more projects than beneficiaries? Just trying to understand the cause...

**Comment by madewild** [comment]
Maybe can be solved by better cache?

**Comment by raphdom** [comment]
@D063520 we could close it because you already improve the cache on beneficiary?

**Comment by D063520** [comment]
I'm still for putting a loader ... I mean it is the same as in the project page ....

**Comment by madewild** [comment]
Indeed let's harmonise. @raphdom I let you reassign

**Comment by raphdom** [comment]
Now we have the loading feature in the beneficiaries list. Can you test, please?

**Comment by madewild** [comment]
Perfect!
