### ISSUE TITLE
Explore GIS options

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#29]
To improve map

**Comment by madewild** [comment]
Also add geolocation option ("projects around me" on mobile)

**Comment by D063520** [comment]
I think I know how to do this. Basically we need the point and this we can get from the IP address. Like described here:
https://www.baeldung.com/geolocation-by-ip-with-maxmind. Would be happy to try this out. Always wanted also for qanswer ....

**Comment by madewild** [comment]
Yes apparently the directors would really love that so please go ahead and experiment :)

**Comment by D063520** [comment]
you can promis this to the directors, but don't promise them the order by budget (this is much more complex) ; )

**Comment by D063520** [comment]
I created a first implementation ..... it is available under
/facet/eu/map/nearby
@raphdom can you try to implement it .... not sure about scalability and so on .....
