### ISSUE TITLE
Pagination not kept during navigation

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#290]
1) visit https://kohesio.eu/beneficiaries
2) change 3 pages
3) click on a beneficary
4) click back (navigation is lost)

**Comment by madewild** [comment]
This is normal behaviour with a server-side pagination...
To change this we would need to encode the page as a get parameter in the url, do we want this?

**Comment by madewild** [comment]
(the user can also open the beneficiary in a new tab...)

**Comment by D063520** [comment]
I think this is what a normal user expects .....

**Comment by madewild** [comment]
OK @omar0z will implement this
also for projects

**Comment by raphdom** [comment]
We have some side effects on this, problem with offset in the pagination @omar0z

**Comment by madewild** [comment]
Indeed, some projects show both on page 1 and on page 2 ! ;)

btw, maybe we could start the count of pages at 1 instead of 0
https://dev.kohesio.eu/projects?page=0 should be https://dev.kohesio.eu/projects?page=1 etc.

**Comment by omar0z** [comment]
Offset has been fixed in #357. After review and approval, OP can close this issue.
