### ISSUE TITLE
Add link to inforegio programme

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#294]
For instance on https://kohesio.eu/projects/Q139379
Currently we have:

Programme: Île-de-France et Seine

we want to have:

Programme: [Île-de-France et Seine](https://ec.europa.eu/regional_policy/en/atlas/programmes/2014-2020/france/2014fr05m0op001)

the backend will provide the URL, cf. https://github.com/ec-doris/kohesio-data/issues/176

**Comment by madewild** [comment]
the url is now provided, cf #307

**Comment by svili** [comment]
Added the link in the commit, just one note for the given project the link now leads to this:
https://ec.europa.eu/regional_policy/opempl/detail.cfm?cci=2014FR05M0OP001&lan=en

Which has the same text as you wanted but kinda unformatted, is this intended?

**Comment by madewild** [comment]
Indeed, let's wait until we have the correct link in the backend to close...

**Comment by madewild** [comment]
Still to be fixed in the backend @DiaZork

**Comment by madewild** [comment]
OK closing, will follow-up in https://github.com/ec-doris/kohesio-data/issues/176
