### ISSUE TITLE
New tab & Firefox

### ISSUE THREAD

**Issue by Bisiaam** [ec-doris/kohesio.eu#297]
When I open a project in a new tab on Firefox, I see a blank page.

![image](https://user-images.githubusercontent.com/85291854/148960845-f29b3fed-9194-43ed-9c37-398fb1a82610.png)

We tried on another computer with @roberto-musmeci and on dev.kohesio but same issue. It works with Chrome

**Comment by madewild** [comment]
I confirm, strange issue... @raphdom any idea what is happening?

**Comment by prototorpedo** [comment]
Same error happens also in other pages in firefox, but doesn't seem to affect the app. Seems like an async / await issue, will attempt to provide a fix

**Comment by prototorpedo** [comment]
Appears to be working if ConfigService is setup as instructed in https://stackoverflow.com/a/47110796

**Comment by raphdom** [comment]
@madewild, @Bisiaam can you test now? should be fine on Firefox

**Comment by madewild** [comment]
Thank you @prototorpedo for your first bugfix and welcome to Kohesio :)

**Comment by Bisiaam** [comment]
Hello,
I still have the issue from my side :/ (and I cleaned the cache)

**Comment by roberto-musmeci** [comment]
> Hello, I still have the issue from my side :/ (and I cleaned the cache)

To me it works properly instead !

**Comment by madewild** [comment]
Same for me, it works... @Bisiaam can you try again tomorrow or Monday?

**Comment by Bisiaam** [comment]
It works :)
