### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#298]
Align with ECL

**Comment by AThollard** [comment]
for info: @gachpas

**Comment by madewild** [comment]
Linked to #302

**Comment by gachpas** [comment]
@AThollard , the A2 Web Team FMB is still refer under contact....it should rather be Alex's team FMB instead, right?

**Comment by gachpas** [comment]
@AThollard , Beaulieu us still mentioned in the REGIO address...to be updated ate DG COMM level?

**Comment by gachpas** [comment]
@madewild , I suppose that it is normal that some links leads to error 404 at the moment, right? (Privacy statement, legal notice, ....)

**Comment by madewild** [comment]
Yes, I will try to make them work by the end of the week...

**Comment by AThollard** [comment]
> @AThollard , the A2 Web Team FMB is still referred under contact....it should rather be Alex's team FMB instead, right?
> 
> Do you know where go the forms that are submitted?
> 
> Also, we should align the different contacts, as our FMB is mentioned in the About page.
> 
> Shouldn't we refer to the GDPR record under "Data protection" in the About page?

After discussion with Max the standard is to refer to a generic page under contact (not even the Webteam actually). Or I have not understood to which 'contact' you refer to.
However, I think we could use the 'about' to mention more specific contacts: Alex's team + our FMB so we are sure to get the messages.
The about section should be revised and the 'data protection' section deleted in the about in  my views as we are covered now by the privacy statement in the footer.
Happy to discuss of course,

**Comment by madewild** [comment]
Now all the links in the footer should work properly.

**Comment by madewild** [comment]
- Linkedin can be removed
- Insta and youtube to be added with the following links:
- [EU in my Region (@euinmyregion) • Instagram photos and videos](https://www.instagram.com/euinmyregion/)
https://www.youtube.com/c/EUinmyRegion

_Originally posted by @gachpas in https://github.com/ec-doris/kohesio.eu/issues/461#issuecomment-1041532336_

**Comment by gachpas** [comment]
@madewild , all working ;)

**Comment by madewild** [comment]
Great, I just need to add a link to the new FAQ page...

**Comment by madewild** [comment]
Done

**Comment by AThollard** [comment]
Sleeping on it, could you please add 'REGIO-KM@ec.europa.eu' in the recipients? Thks

**Comment by AThollard** [comment]
OK, leave it like that then. We will organise ourselves internally
