### ISSUE TITLE
Harmonize numerical formats

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#30]
Decimal and thousand separators should be the same across the site, including:

- carousel
- key figures
- homepage map
- projects
- beneficiaries

**Comment by madewild** [comment]
All the monetary amounts now seem correct.
The only remaining question is for the co-financing rate: should we have a comma instead of a dot when there are decimals? I'll ask Pascal.

**Comment by madewild** [comment]
REGIO confirms that we have to use the comma everywhere as a decimal separator

**Comment by raphdom** [comment]
Fixed
