### ISSUE TITLE
Change default sort

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#300]
on https://dev.kohesio.eu/projects the default sort should remain "no sort" (just rename it to "Relevance"), i.e. images first
but when using filters and/or keywords, the default sort should be "Total Project Budget (descending)"
the backend will reflect this change

**Comment by madewild** [comment]
@AThollard @roberto-musmeci you can test with a keyword or a filter on https://dev.kohesio.eu/projects
@svili there is still a side effect: if you select a sort criterion on the main page and then go back to "no sort", it still tries to filter by decreasing budget (which currently fails because cache is missing, cf. https://github.com/ec-doris/kohesio-backend/issues/97)

side note: could we rename "Total Project Budget" to just "Total Budget" or even "Budget"? The URL gets very long with this...

**Comment by svili** [comment]
In #325 the side effect should be fixed (along with the name).

**Comment by madewild** [comment]
Closing, @roberto-musmeci feel free to reopen if something is not as expected.
