### ISSUE TITLE
program filter on the facets not working

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#303]
In the project search the program filter is not opening. I guess the API is not called.

<img width="685" alt="Screenshot 2022-01-21 at 17 06 27" src="https://user-images.githubusercontent.com/10883585/150560190-9074ba71-c7ff-46aa-b887-73f2c5485b5c.png">

**Comment by madewild** [comment]
@svili could you check?

**Comment by svili** [comment]
So actually the programme name filter works, but only when a country is selected.
I can make it work without country selected if thats what you'd like?
![image](https://user-images.githubusercontent.com/11196689/150783711-87f909c7-c16d-40c4-a6f7-00be3dc6e03e.png)

**Comment by madewild** [comment]
ah yes it's normal, see #284
we should add a placeholder text "Select country first" in both Region and Programme
so no issue here
