### ISSUE TITLE
Harmonise budget terminology

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#320]
1. On https://kohesio.eu/projects
    - in the sort menu
        - Total Project Budget (ascending) -> Budget (ascending)
        - Total Project Budget (descending) -> Budget (descending)
    - in the search results (below the actual amount)
        - Total project budget -> Budget
    - in the advanced filters
        - TOTAL PROJECT BUDGET > BUDGET
2. On https://kohesio.eu/projects/Q139379 (for instance)
    - Total budget > Budget
    - Funded by EU > EU contribution
3. On https://kohesio.eu/beneficiaries
    - I suggest here we leave "Total Budget" because it's really a total (sum)
4. On https://kohesio.eu/beneficiaries/Q2514974 (for instance)
    - Funded by EU > EU contribution

To be validated by @slaven777 first

**Comment by madewild** [comment]
@slaven777 do you confirm ths new terminology is OK from a communication point of view?

**Comment by slaven777** [comment]
can we make it "Total budget"? I see that the online generator, another REGIO project that prepares billboards and plaques uses the "Total budget", so aiming to have the same info in Kohesio and on billboards and plaques of actual projects

**Comment by madewild** [comment]
We can if necessary, but as a citizen I don't understand what the "total" is about.
For beneficiaries on the contrary (e.g. https://kohesio.eu/beneficiaries/Q2514974) "Total budget" totally makes sense because it's the sum of the budgets of several projects.
Anyway @slaven777 the final decision is yours to take. :)

**Comment by slaven777** [comment]
okay, lets keep "Total budget" as it's in line with other platforms

**Comment by madewild** [comment]
@svili can you adapt again everywhere?

**Comment by madewild** [comment]
Fixed, @slaven777 can you check that it is applied everywhere? If not feel free to reopen.
