### ISSUE TITLE
ordering when clicking on thematic objective (TO) and search is not harmonized

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#323]
- search for TO in search triggers order by budget
- click on icon of TO (from the homepage) triggers no order

**Comment by svili** [comment]
Can you guys elaborate on this?
We implemented default ordering by budget on purpose.
But the second one I don't understand.

**Comment by madewild** [comment]
To adapt on https://dev.kohesio.eu/ and https://dev.kohesio.eu/themes
I discussed with @svili

**Comment by madewild** [comment]
@svili it's fixed on the homepage but not on https://dev.kohesio.eu/themes

**Comment by madewild** [comment]
@svili this still uses "Budget (descending)" instead of "Total Budget (descending)"!

**Comment by svili** [comment]
Where? Can you do a hard refresh? Cause I can't find it.

**Comment by madewild** [comment]
Oops my bad, it was indeed cached on my side ;)
Fixed.
