### ISSUE TITLE
When clicking on a point on the map, two requests are done

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#326]
If I'm not wrong, two requests are done for each selected point on the map ....

**Comment by madewild** [comment]
I see only one request:
![point](https://user-images.githubusercontent.com/942488/151793871-230153c9-b4f3-4f98-be49-610f34754210.png)

can you elaborate?

**Comment by D063520** [comment]
https://user-images.githubusercontent.com/10883585/151858464-a00c49e1-55aa-4b0f-bb0f-f28f7d45d238.mov

**Comment by D063520** [comment]
https://user-images.githubusercontent.com/10883585/151858823-606755e4-8770-4e76-862b-b823fff74d74.mov

**Comment by madewild** [comment]
This is with Safari? I cannot replicate with Chromium nor Firefox...

**Comment by D063520** [comment]
yes, this is with safari, could be a browser dependent problem. You can close it if it is like this ...

**Comment by madewild** [comment]
Old thread but seems to be something like that: https://stackoverflow.com/questions/5956501/safari-double-submitting-ajax-calls
