### ISSUE TITLE
Implement outermost regions ribbon on projects results (map tab)

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#328]
![results_map](https://user-images.githubusercontent.com/942488/152133108-fb0491a5-0c85-48fa-a8b7-05af420a2bfe.png)

interaction with filters...

**Comment by madewild** [comment]
Follow-up to #234

**Comment by raphdom** [comment]
it was implemented in the project list, I think we can close this @madewild ?

**Comment by madewild** [comment]
It's quite slow in dev but that's related to the (unlimited) live index.
Closing now, will reopen if there is a problem after merging to test.
