### ISSUE TITLE
Adapt carousel to ECL

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#342]
And activate auto-rotate

**Comment by madewild** [comment]
Follow-up to #239

**Comment by madewild** [comment]
See https://ec.europa.eu/component-library/ec/components/carousel/code/

**Comment by madewild** [comment]
speaking about the carousel, do you have th epossibility to have the same kind of carousem that the one used for the countdown page (i.e. the width of the carousel is aligned on the width of th emap and the little arrow (allowing to navigate the carousel) are part of the carousel (and not outside of teh carousel)? I ncase @AThollard , confirms this choice, it could be for another version if too complicated for now....

_Originally posted by @gachpas in https://github.com/ec-doris/kohesio.eu/issues/239#issuecomment-1029772543_

**Comment by madewild** [comment]
Note: on https://ec.europa.eu/info/index_en they have a wider carousel, to evaluate...
But indeed it does not stop when you hover or click :(

**Comment by madewild** [comment]
Thanks @omar0z for this first working version! Here are a few improvements:

- [ ] remove text-decoration:underline on the buttons texts
- [ ] align play/pause button vertically with "1 of 3"
- [ ] check if images should be resized to avoid cropping them too much (compare with https://kohesio.test.ec.europa.eu/)
- [ ] Enjoy Kohesio's... -> Check Kohesio's...
- [ ] open and linked data -> linked and open data
- [ ] export Kohesio's datasets -> get the datasets

**Comment by madewild** [comment]
I already adapted the texts.
The first two things are defined in ecl-ec.css so I guess we need to define some custom css that has precedence over ECL.

For the text-decoration:

```css
.ecl-link--icon:not(.ecl-link--standalone) .ecl-link__label {
    /* text-decoration: underline; */
}
```

For the play-pause button:

```css
.ecl-page-header-harmonised .ecl-container>:first-child:not(.ecl-page-header-harmonised__breadcrumb) {
    margin-top: 0;
    /* padding-top: 2rem; */
}
```

**Comment by raphdom** [comment]
Fix the two first points

**Comment by madewild** [comment]
The padding is indeed fixed but the text in the button is still underlined... it should never be underlined.

**Comment by raphdom** [comment]
It is aligned with the link call to action from ECL:

https://ec.europa.eu/component-library/ec/components/navigation/link/code/

Why this should never be underlined?

**Comment by madewild** [comment]
Mmmh, it was not underlined on https://kohesio.test.ec.europa.eu/ and I found it much better. For me it's strange to have underlined text inside a button. It would prefer something like the button/tab "My Trade Assistant" on https://trade.ec.europa.eu/access-to-markets/en/home but as you wish.

**Comment by raphdom** [comment]
They have a button and a link, the link has underlined text and the cursor to indicate that will go somewhere else, the button doesn't have that means that will perform an action inside the page, at least this is my interpretation of this. But as you want, we can always change of course... We could remove the underline and in the hover keep?

**Comment by madewild** [comment]
I would remove the underline always and only change the button color on hover (like on https://kohesio.test.ec.europa.eu/).
But don't lose too much time with this, we have more urgent things to tackle ;)

**Comment by madewild** [comment]
@omar0z the link is still underlined when hovering the button... or is it a cache issue again?

**Comment by raphdom** [comment]
@madewild I've tried to change the button inside the carousel, but with the button instead of the link we will loose the cursor and the hover, I think for now we can leave like that and move on, in the feature we can improve? what do you think?

**Comment by madewild** [comment]
OK, then there is only the issue of cropped images...

**Comment by raphdom** [comment]
@omar0z can you check this? please

**Comment by madewild** [comment]
Not sure there is an easy solution to this... I will close and open a separate issue, to check with REGIO designers.

**Comment by omar0z** [comment]
Or maybe we could try and play with the opacity of the controls strip of the carousel, but that might be some work for not much gain IMO
