### ISSUE TITLE
Add new logo

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio.eu#347]
Kohesio: discover EU projects in your region (one row)
If ready and possible add the logo.
@madewild

**Comment by madewild** [comment]
There is no title, only a logo, right?
Waiting for the logo then. :)

**Comment by AThollard** [comment]
Right @madewild, just the title
And let's add the logo with the ECL to see where it fits.
We have already chosen
![Kohesio_signature-10](https://user-images.githubusercontent.com/80402472/152558875-e9bedfdc-bc40-4321-9033-fbc78d8bbc83.png)

**Comment by madewild** [comment]
I already changed the title and subtitle. I move to 1.1 for the logo...

**Comment by madewild** [comment]
@AThollard not so easy to see where the logo will fit in the ECL template...
check https://digital-strategy.ec.europa.eu/en for instance

**Comment by madewild** [comment]
Now we can see for real on https://kohesio.development.ec.europa.eu/
No idea where to put the logo :-/

**Comment by AThollard** [comment]
Can you modify the first banner for the logo? I fear not...
![image](https://user-images.githubusercontent.com/80402472/154029443-e21e83c0-db15-45e2-a4c0-31053d55a95a.png)

**Comment by madewild** [comment]
I don't think so... other examples of websites using ECL:

https://ec.europa.eu/food/index_en
https://ec.europa.eu/oceans-and-fisheries/ocean_en
https://trade.ec.europa.eu/access-to-markets/en/home

**Comment by madewild** [comment]
I will do a few tests but not sure there is a good solution.

**Comment by madewild** [comment]
I managed to squeeze the logo in the footer:
![logo_footer](https://user-images.githubusercontent.com/942488/154574392-eaecf101-de51-45ed-99cf-a41b07e26524.png)

you can check on https://kohesio.development.ec.europa.eu/
not the most visible place but better than nothing ;)

**Comment by AThollard** [comment]
Perfect @madewild ! Logo is not the main message we want to pass with Kohesio
