### ISSUE TITLE
Add page listing services

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#351]
Let's centralise our offer of services in a new page (/services for instance ?):

- query service that will be on https://kohesio.ec.europa.eu/query
- question answering service that will be on https://kohesio.ec.europa.eu/qa
- data exports service that will be on https://kohesio.ec.europa.eu/data
- EU Knowledge Graph that is on https://linkedopendata.eu (or https://knowledgegraph.eu)

I will provide the texts.

**Comment by madewild** [comment]
After discussing with @AThollard we will keep the /services page (@prototorpedo can you prepare the skeleton?) but change the contents, I will take care of this.

**Comment by madewild** [comment]
It's a static page, now I know how to do it myself :)

**Comment by madewild** [comment]
Done, can be improved later.

**Comment by madewild** [comment]
After discussion with Dennis we chose to leave only these for the first release:
![services_new](https://user-images.githubusercontent.com/942488/154569135-5b313238-568b-4049-9996-170d1416b904.png)

cf. https://kohesio.development.ec.europa.eu/services
@AThollard fine for you?
(the data page is not ready yet)

**Comment by AThollard** [comment]
Fine. thanks.
