### ISSUE TITLE
Move countdown to prod

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#352]
Countdown is currently on https://kohesio.acceptance.ec.europa.eu/
When validated it should move to https://kohesio.ec.europa.eu/ until the launch
@AThollard can you give the green light and ideal date for the switch? Monday 7/2?
Then we can use acceptance for the BERL demo...

**Comment by AThollard** [comment]
Hi @madewild, countdown version ready.
You can already put it on https://kohesio.ec.europa.eu/ or Monday if more convenient for you.
And then yes demo on:https://kohesio.acceptance.ec.europa.eu/ Monday 07/02 would be perfect so I can prepare in the real environment.
info: @gachpas

**Comment by raphdom** [comment]
The countdown is on prod now: https://kohesio.ec.europa.eu/
I am preparing the acceptance for monday. Waiting for a stable version to freeze and put on acceptance for your presentation @AThollard

**Comment by AThollard** [comment]
The Portuguese commissioner [Elisa Ferreira](https://ec.europa.eu/commission/commissioners/2019-2024/ferreira_en) counts on us @raphdom!
No pressure, have a nice week-end!

**Comment by raphdom** [comment]
@AThollard you can mention there is a portuguese in the team, she will be very happy. :) lol
Have a nice week-end!

**Comment by AThollard** [comment]
We could prepare a slide with the extended Kohesio Team photos, and related nationalities :-)

**Comment by madewild** [comment]
@raphdom the font size is much larger on https://kohesio.ec.europa.eu/ compared to https://kohesio.acceptance.ec.europa.eu/, is this normal?

**Comment by raphdom** [comment]
@madewild the acceptance you have the old version probably cached...

**Comment by madewild** [comment]
ah ok, now I see indeed kohesio website in acceptance...
but the font still appears huge to me in prod:
![huge](https://user-images.githubusercontent.com/942488/152579913-117c6a64-6720-4362-b410-4083353e8f97.png)
@AThollard @djang0 this is as expected?

**Comment by Djang0** [comment]
@madewild indeed @AThollard asked for bigger title. So I supercharged bootstrap's css (since this is already a h1). I can revert back to the standard (as it was before). just tell me.

**Comment by Djang0** [comment]
@madewild I created a branch to revert back to standard https://github.com/ec-doris/kohesio-countdown/tree/pure_bootstrap checkout the one you and @AThollard will choose. have a nice weekend

**Comment by madewild** [comment]
Let's keep the size and change the text to:

Kohesio
Discover EU projects in your region

**Comment by AThollard** [comment]
Discussed with @madewild so ok for me to change the text as mentioned @Djang0

**Comment by AThollard** [comment]
Thanks for adding a link to https://ec.europa.eu/regional_policy/en/, on the text :"Directorate-General for Regional and Urban Policy" @Djang0

**Comment by madewild** [comment]
All good on prod: https://kohesio.ec.europa.eu/

**Comment by Djang0** [comment]
Github notifications arriving on my personal mailbox. Juste saw it :)
