### ISSUE TITLE
Bug displaying project details for highlighted projects on map

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio.eu#356]
On dev.kohesio.eu if you click on some 'highlighted' project (red) on the map the project details page is not displayed.
![image](https://user-images.githubusercontent.com/80402472/152550895-26536483-16b5-4abc-b19f-6b5c8b4f41a6.png)

**Comment by AThollard** [comment]
@madewild

**Comment by madewild** [comment]
@D063520 @DiaZork https://dev.kohesio.linkedopendata.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q148455 is giving gateway timeout

**Comment by madewild** [comment]
Working now, @AThollard can you check?

**Comment by AThollard** [comment]
All good @madewild, you can close the issue
