### ISSUE TITLE
Improve carousel

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#36]
The carousel could be thinner, which would allow to see better the map and key figures.
Also, the images in the carousel are a little bit blurry: let's obtain them in better resolution.

**Comment by teodoracostin** [comment]
Fixed the height, soon will be merged on master. I will ask for better quality images to integrate.

**Comment by raphdom** [comment]
Fixed!

**Comment by madewild** [comment]
The image is still blurry on my large screen, can we get a better resolution?
![blurry](https://user-images.githubusercontent.com/942488/86436702-139f9b00-bd03-11ea-81fc-986bd138ab19.png)

**Comment by teodoracostin** [comment]
I have asked BISIAUX Amaury to provide us images with better resolution. I will integrate them once I receive them.

**Comment by madewild** [comment]
OK no problem, let's just keep this issue open until it's fixed :)

**Comment by teodoracostin** [comment]
Images on carousel are with better resolution now.

**Comment by madewild** [comment]
For me the first image is still blurry
And apparently the carousel is not thin enough
Reopening and moving to v2

**Comment by teodoracostin** [comment]
Hi,

I have updated the carousel 50% text 50% img like Pascal asked.
Changes are on branch d-carousel pushed to dev.
