### ISSUE TITLE
Flag CSS

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#37]
When the beneficiary name spreads over multiple lines, the national flag shrinks

**Comment by madewild** [comment]
I cannot really reproduce this issue, ask Thierry

**Comment by raphdom** [comment]
I cannot reproduce also

**Comment by raphdom** [comment]
![image](https://user-images.githubusercontent.com/5124917/86091927-fd000680-baac-11ea-8c3e-72ab88a5d70f.png)

**Comment by raphdom** [comment]
![image](https://user-images.githubusercontent.com/5124917/86092813-53ba1000-baae-11ea-9099-51ee58e6a4b7.png)

**Comment by raphdom** [comment]
Firefox!

**Comment by raphdom** [comment]
Fixed!
