### ISSUE TITLE
Map behaviour 

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio.eu#374]
Hi guys, 

hopefully two small bugs 
I noticed a change in the behaviour of the Map. 

In dev, the NUTS layer is not displayed in the project fiche. As a result, the map does not zoom in on the project. 
- https://kohesio.eu/projects/Q3105597
- https://dev.kohesio.eu/projects/Q3105597
left(prod) - right(dev)
![image](https://user-images.githubusercontent.com/86654885/152782485-06f8fffc-529b-4458-bd36-13025aa351c8.png)

-----
Also, we miss a piece of Poland 
![image](https://user-images.githubusercontent.com/86654885/152781753-3cbbacb6-9b5a-4991-931d-c58243c070ad.png)

**Comment by madewild** [comment]
1. NUTS is fine on https://linkedopendata.eu/wiki/Item:Q3105597 so looks like a backend issue

This is what I see in the console:
core.js:4197 ERROR Error: Bounds are not valid.

2. Also backend issue, Pomeranian Voivodeship is fine on https://linkedopendata.eu/wiki/Item:Q2530082 but the geojson is empty in https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/project/map?granularityRegion=https://linkedopendata.eu/entity/Q13

**Comment by madewild** [comment]
Actually it looks like the same issue (or at least related), because for the first problem the reason is also that geojson is empty but this time in https://dev.kohesio.linkedopendata.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q3105597

@DiaZork can you investigate?

**Comment by madewild** [comment]
Sorry guys, a bit urgent because @raphdom needs to redeploy this to ACC before demo to Commissioner on Wednesday...

**Comment by D063520** [comment]
It was me ... I did it because absically we use two sparql endpoints ... one is the one over the projects. The other one is the one containing the nuts. This one is currently not in the live endpoint. It was down and then nothing was rendering. It is back again
