### ISSUE TITLE
link of 3rd carousel section

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#376]
Currently the 3rd carousel link is pointing to:

https://data.linkedopendata.eu

It's a non very ui freindly page .... what about putting:

https://linkedopendata.eu

There are links on how to download the data and also to query it via sparql .....

**Comment by madewild** [comment]
Duplicate of #343 ;)
Yes we could put this for now...

**Comment by madewild** [comment]
Changed on https://dev.kohesio.eu/
