### ISSUE TITLE
Rename Edit button

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#379]
@AThollard in the end should we rename the Edit button visible on https://dev.kohesio.eu/projects/Q139379 for instance?
One suggestion would be to call it "More", a bit more neutral ;)

**Comment by AThollard** [comment]
Yes, please go ahead with 'More'

**Comment by madewild** [comment]
@svili maybe we also need a new icon as a writing pen is convenient for "Edit" but not really for "More"...

also present on beneficiaries like https://dev.kohesio.eu/beneficiaries/Q2514974
so should be changed in two places

**Comment by madewild** [comment]
So if we want to use "More details" to replace "Discover in InforRegio", here are other suggestions for the Edit button:

- **Source** (but this sounds a bit like source code of the page)
- **Data** (I like this one since it's going to linkedopen**data**.eu)
- ...

@AThollard @roberto-musmeci what do you think?

**Comment by svili** [comment]
![image](https://user-images.githubusercontent.com/11196689/153559851-98f87e61-6e81-4014-9a4e-3ffc0f60e174.png)
or maybe 
![image](https://user-images.githubusercontent.com/11196689/153559947-a762adcb-84ff-4001-9f00-92ad556ab790.png)
?

**Comment by madewild** [comment]
I prefer the 3 dots, but let's wait to see if we keep "More" or "Data" or something else ;)

**Comment by roberto-musmeci** [comment]
I agree with the tree dots. 
For the link to info regio we could use "Read further about the project" (too long ?). In this way we can use "More"
