### ISSUE TITLE
highlighted projects are covered

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#382]
Theory: the sharp eye of Jonathan saw that some points are more red then others. Can you check in the UI if you are covering the red points

<img width="1680" alt="Screenshot 2022-02-08 at 18 08 52" src="https://user-images.githubusercontent.com/10883585/153039013-3035e301-95a6-469f-8521-332367817de4.png">

PS: also in the backend response we see more highlighted projects that we see on the map

Above is Denmark : )

**Comment by D063520** [comment]
it was a backend problem ....

**Comment by madewild** [comment]
OK cool, DK looks much better now :)
![dk](https://user-images.githubusercontent.com/942488/153073749-e0f98580-446c-494b-8231-cd77554e9599.png)
