### ISSUE TITLE
Change text hyperlink to Info Regio page

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio.eu#387]
As suggested by A2 Director, we should change the text "Discover more in Info Regio" in something more like "more details". 

![image](https://user-images.githubusercontent.com/86654885/153456615-f44eba2a-62a2-4803-a0ee-3044d5a8c6d4.png)

**Comment by madewild** [comment]
OK but we already agree to transform "Edit" into "More" (cf. #379) so that might be confusing... Let's find something more specific. :)
