### ISSUE TITLE
Breadcrumb adaptation in all pages

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#397]
New ecl component to breadcrumb in all pages, can be simple right now, to be improved for next version

**Comment by raphdom** [comment]
you forgot about the themes page

**Comment by madewild** [comment]
There is also:

https://kohesio.development.ec.europa.eu/about
https://kohesio.development.ec.europa.eu/privacy

**Comment by omar0z** [comment]
@madewild What about it? I can see the breadcrumbs there

![image](https://user-images.githubusercontent.com/2214957/154268625-08117ec6-b30a-4f66-a558-60189faec209.png)

**Comment by omar0z** [comment]
Also on privacy
![image](https://user-images.githubusercontent.com/2214957/154268735-9c629251-0450-4510-9e51-1436838193bc.png)

**Comment by madewild** [comment]
ok sorry was probably a cache issue on my side...
