### ISSUE TITLE
Themes component homepage

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#401]
- Align the design with ECL
- Responsive Design

**Comment by madewild** [comment]
Fine for me on https://kohesio.development.ec.europa.eu/themes

**Comment by madewild** [comment]
Confusion with #402 
The other one is solved but this one we still need

**Comment by raphdom** [comment]
@svili for me we could align the margins on desktop and mobile with the other elements in the page, carousel and map.
another thing that I thing it will be better is decrease the margin between the cards on desktop version (columns)

**Comment by madewild** [comment]
Also, the link behind "Explore more..." is now https://kohesio.development.ec.europa.eu/projects?theme=Climate-Change-Adaptation-%26-Risk-Prevention&sort=Total-Budget-(descending) instead of https://kohesio.development.ec.europa.eu/themes

**Comment by madewild** [comment]
(I already fixed the last point)

**Comment by madewild** [comment]
As discussed:

- [ ] Change color to blue
- [ ] Align left and right to the map
- [ ] Don't hardcode PO and TOs
- [ ] Remove explore more card and move to call for action
- [ ] (remove Themes h2?)

**Comment by raphdom** [comment]
Seems to be fine now, we need to remove the h2?

**Comment by madewild** [comment]
The last one is covered by #483
