### ISSUE TITLE
About page - Side effects

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#404]
- Align ECL design
- Responsive Design

**Comment by madewild** [comment]
The CSS seems strange to me (black text, strange heading styles) 
@raphdom this is for later? can I close here?

**Comment by madewild** [comment]
https://kohesio.development.ec.europa.eu/about

**Comment by raphdom** [comment]
No, normally for the typography we need to apply the rules from ECL:
@svili the <h1> and <p> tags are not enough, you need to use:
`<h1 class="ecl-u-type-heading-1">`
or
`<p class="ecl-u-type-paragraph">`

Please check the documentation:

https://ec.europa.eu/component-library/ec/utilities/typography/usage/

**Comment by raphdom** [comment]
we can close this @madewild ?

**Comment by madewild** [comment]
Indeed, for the contents change we will follow-up in #222
