### ISSUE TITLE
Filters Sidenav - Side effect

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#405]
Fix the sidenav for the filters on projects and beneficiaries list page
Responsive design

**Comment by madewild** [comment]
@raphdom mostly fine but the intervention fields are missing (we only have the section headers). Should I open a separate issue for this or will you follow-up here?

**Comment by madewild** [comment]
also, the help tooltips to explain how to use 1. keywords and 2. type of beneficiary (public/private) are missing

**Comment by raphdom** [comment]
Yeah, maybe is a good idea, open 2 new issues. I will do it.
