### ISSUE TITLE
Project List Design

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#407]
Fix the design of the project list
Responsive design also
Wait Raphael to fix the sidepane and the filters

**Comment by prototorpedo** [comment]
Are sidepane and filters fixed @raphdom ?

**Comment by madewild** [comment]
Yes: #405

**Comment by raphdom** [comment]
For me still some points to adjust:

- [ ] Remove the space between the image on the card
- [ ] Remove the margin on the footer(grey area)
- [ ] On the footer of the card, the font of the "Total budget" seems Italic, need to align the test environment
- [ ] Same for the font-size of the value of the Total Budget
- [ ] The sort should be in the same position as it is in the beneficiaries list

**Comment by madewild** [comment]
Yes, I was about to comment on the font sizes (we have 12px, 13px and 16px in the same card). Maybe let's have 14px everywhere. The "Total budget" was already italics in test but not sure we need it... And we miss the "clock" icon just before the dates.

**Comment by prototorpedo** [comment]
I tried to make it exactly as on test. If you check there, those are the font sizes used

**Comment by madewild** [comment]
Yes, test is an inspiration but we should not stick too much to the exact font sizes... the font has changed and the goal is to make it nicer and harmonized. :)

**Comment by prototorpedo** [comment]
I felt it looked nicer on test, also why I kept the font sizes.
Regarding the icon, the EclIconModule wasn't imported and wasn't sure what I needed to import. I see now in the documentation it's a component.

**Comment by prototorpedo** [comment]
> * [ ]  Remove the space between the image on the card
What image are you referring to? The photo of the project?
> * [ ]  Remove the margin on the footer(grey area)
Are you referring to top and bottom margin of the grey little box? If so, I would need to add padding
> * [ ]  On the footer of the card, the font of the "Total budget" seems Italic, need to align the test environment
Total budget is italic on test
> * [ ]  Same for the font-size of the value of the Total Budget
Will use same font size for all text there, as per @madewild request
> * [ ]  The sort should be in the same position as it is in the beneficiaries list
Am I missing something? It's in the same position

**Comment by raphdom** [comment]
What image are you referring to? The photo of the project?
The photo of the project, we have a lot of blank space on left and right

Are you referring to top and bottom margin of the grey little box? If so, I would need to add padding
Yes, we need to have the same spacing as we have on test, smaller, otherwise the card will be bigger(height)

Total budget is italic on test
We have some strange letter-spacing...

Will use same font size for all text there, as per @madewild request
The letter-spacing is also not nice.

The sort should be in the same position as it is in the beneficiaries list
I know that I am pick, but should be more close to the pagination?

**Comment by prototorpedo** [comment]
Ah, indeed, I used letter spacing for the amount bc the difference between them was quite staggering, on dev it's bundled together, thought it was very ugly.

**Comment by prototorpedo** [comment]
All points should be addressed in latest PR

**Comment by madewild** [comment]
Yes much better, good enough for now.
Thanks @prototorpedo !

**Comment by prototorpedo** [comment]
It just dawned on me I could have used material icons for the clock. Maybe we can use material icons since they're already there?
