### ISSUE TITLE
Project Details Design - Side effect

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#408]
Fix the design of the page detail
Responsive design

**Comment by raphdom** [comment]
As I did the beneficiary page. I will do it. It will be more easy...

**Comment by madewild** [comment]
The location over the map (e.g. "In Zielonogórski, Poland") could also be an h4 or even h5...

**Comment by raphdom** [comment]
it is

**Comment by madewild** [comment]
ah yes, much better now :) maybe I still had an old version in cache (with h2)

**Comment by raphdom** [comment]
done, can you test @madewild?

**Comment by madewild** [comment]
Very nice!
