### ISSUE TITLE
Beneficiary List Design - Side effect

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#409]
Fix the design of the beneficiary list
Currencies broken
Wait for Raphael to fix the sidenav and the filters

**Comment by raphdom** [comment]
fixed, can you check @madewild

**Comment by madewild** [comment]
Fine for me except that the rendered font looks a bit strange
Also there is an error in the console on https://kohesio.development.ec.europa.eu/beneficiaries
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'

**Comment by raphdom** [comment]
now is good, closing...
