### ISSUE TITLE
Beneficiary detail - Side effect

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#410]
- Design
- Responsive design

**Comment by raphdom** [comment]
working on that, some improvements already, miss some styles and the responsive design...

**Comment by madewild** [comment]
Start and end date are still missing on https://kohesio.development.ec.europa.eu/beneficiaries/Q2514974, compare with https://kohesio.test.ec.europa.eu/beneficiaries/Q2514974

**Comment by madewild** [comment]
And also: for the name of the beneficiary, I suggest using `class="ecl-u-type-heading-4"` (the current style is much too big)

**Comment by raphdom** [comment]
both are fixed, can you check again @madewild

**Comment by madewild** [comment]
Perfect now.
