### ISSUE TITLE
Pagination and tabs query params - side effect

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#413]
Doesn't work anymore
Wait for Raphael to fix sidenav and tabs

**Comment by raphdom** [comment]
fixed on projects and beneficiaries page, we don't have the tab=results anymore, per default is results, we don't need to put in the query params. The same for page=1, I remove because it is the default. @madewild if it is okay you can close the other issues also (https://github.com/ec-doris/kohesio.eu/issues/361)

**Comment by madewild** [comment]
Very nice like this!
