### ISSUE TITLE
Text overlap

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#42]
Amounts overlapping on small screens:
![overlap](https://user-images.githubusercontent.com/942488/85866194-532c2b80-b7c7-11ea-8102-74a6055ba4e8.png)

Quick fix or wait for responsive design?

**Comment by teodoracostin** [comment]
Responsiveness will fix this issue.

**Comment by madewild** [comment]
Great!
And good to see you can comment here :)
So we move to v2 when mobile is implemented

**Comment by raphdom** [comment]
fixed
