### ISSUE TITLE
Markers on the map are too large

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#43]
They are hiding the actual map (country). Can we make them always smaller, or relative to the size of the zoom?
![too_large](https://user-images.githubusercontent.com/942488/86000456-dd65d100-ba0d-11ea-958d-80821c3750f7.png)

**Comment by madewild** [comment]
Another telling example with Corsica projects:
![corse](https://user-images.githubusercontent.com/942488/86436515-b3a8f480-bd02-11ea-96bf-8521c8b4595c.png)

**Comment by raphdom** [comment]
fixed!
