### ISSUE TITLE
Main map - side effect

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#432]
With the reduced width, Cyprus is hidden by the Leaflet credits:
![cyprus_hidden](https://user-images.githubusercontent.com/942488/154017773-542723f5-ecca-49f2-9af3-5b8332874ba5.png)

I would suggest changing the default minimum longitude to have something like this:
![cyprus_leaflet](https://user-images.githubusercontent.com/942488/154017870-579f54a9-081d-4a7b-9a43-3fae81fe96e6.png)

**Comment by raphdom** [comment]
Should be fine now. You can test @madewild

**Comment by madewild** [comment]
Almost good but when we hover the word "project" is still behind Leaflet... could we move further to the left? No problem if we hide Azores since it's an outermost region.

**Comment by raphdom** [comment]
I cannot push more otherwise in the tablet mode Portugal will be cutted. 768ox. Please check @madewild

**Comment by madewild** [comment]
Perfect now!
