### ISSUE TITLE
Strange rendering for loading beneficiaries

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#437]
The rendering is a bit strange (loading over the table header)

_Originally posted by @madewild in https://github.com/ec-doris/kohesio.eu/issues/418#issuecomment-1040198512_

**Comment by madewild** [comment]
![benef_loading](https://user-images.githubusercontent.com/942488/154060593-2bcbe159-5825-4a0e-b310-450e95f9e672.png)

**Comment by raphdom** [comment]
done

**Comment by madewild** [comment]
writing "fix" in the PR also automatically closes the issue ;) but it's fine in this case, I confirm it works
