### ISSUE TITLE
Advanced Filter expanded rules

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#442]
The advanced filters should be expanded when we have values filled inside, specially when the page loads with queryparams.

**Comment by raphdom** [comment]
done. Can you test @madewild ?

**Comment by madewild** [comment]
If I select a fund for instance, close the advanced filters and press show results, then the advanced filters stays closed.
But if I then refresh the pages, it opens. Is that the intended behaviour? Fine for me.

**Comment by raphdom** [comment]
it was like that before, we open when you refresh the page only
