### ISSUE TITLE
Improve CSS of project list in map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#449]
The css of the list of projects is quite bad:
![map_proj_css](https://user-images.githubusercontent.com/942488/154140164-07f374e0-6720-4f98-bc40-f29a41cd090a.png)

Align more with https://kohesio.test.ec.europa.eu/ (European blue, underline on hover, wider box to avoid too much horizontal scrolling...)

_Originally posted by @madewild in https://github.com/ec-doris/kohesio.eu/issues/400#issuecomment-1040737838_

**Comment by raphdom** [comment]
This is already done also.

**Comment by madewild** [comment]
Excellent.
