### ISSUE TITLE
Re-enable bubbles/clusters on the map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#45]
When we have 20 markers at the same location, find a mechanism to display them all nicely
Cf. https://www.storelocatorwidgets.com/blogpost/20465/Marker_clustering_added_to_MapBox_and_Open_Street_Map

**Comment by raphdom** [comment]
When we have more than one project we display it in the popup in a scroll if needed. Still need to improve and ask Dennis to create another endpoint to receive the coordinates and retrieve all the projects in this coordinate.
