### ISSUE TITLE
Carousel images ratio

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#468]
The images have been designed for the previous eUI viewport and now the carousel is much narrower... Sorry about that, can the designers help to have something nicer on https://kohesio.development.ec.europa.eu/ ? Currently we just crop the images...

https://kohesio.test.ec.europa.eu/assets/images/banners/kohesio-citizens.png
https://kohesio.test.ec.europa.eu/assets/images/banners/kohesio-policy.png
https://kohesio.test.ec.europa.eu/assets/images/banners/kohesio-data.png

**Comment by madewild** [comment]
Is it because the blue strip of the controls is over the image? Then if that is the issue, don't ask them to make the image smaller, otherwise the component will adjust to the new aspect ratio and then it will still crop the image to show the controls. The image should be the same as right now, but leaving a blank space in the bottom to accommodate the carousel control overlay, so the scene is not affected.

_Originally posted by @omar0z in https://github.com/ec-doris/kohesio.eu/issues/342#issuecomment-1041829169_

**Comment by omar0z** [comment]
I would add to the above that if an empty space is added at the bottom of the banners, while keeping the same dimensions, then the entire scene should be scaled down so it is displayed properly in the component without crops.

**Comment by madewild** [comment]
Then I could try to do that myself...

**Comment by madewild** [comment]
I tried with this image but the result is exactly the same:
![kohesio-citizens-test](https://user-images.githubusercontent.com/942488/154345882-95e97e15-f3fd-4b1d-82c3-4fb411dbe068.png)

So I think the problem is not the controller bar: the image adjusts to the width and then the bottom is cropped
@gachpas can we have a quick chat with the image designers tomorrow to check the options?

**Comment by gachpas** [comment]
@madewild , invitation sent out for a 15 min meeting with the graphic designer.

I could not confirm with her if the lot is Ok , as she is "away" in skype but her agenda is free in teh slot I have planned...let's cross the fingers ;)

**Comment by madewild** [comment]
Thanks to Chloe we have much better visuals now :)
https://kohesio.development.ec.europa.eu/
@AThollard I slightly adapted the carousel texts for better rendering, let me know what you think...

**Comment by AThollard** [comment]
Much better, thanks

**Comment by madewild** [comment]
@AThollard here's a new proposal for the first card:
![car1_new](https://user-images.githubusercontent.com/942488/154568564-969bb00a-5b74-42de-a96b-8fa1de945b4d.png)

**Comment by AThollard** [comment]
I was about to propose 'find-out' as well this morning @madewild 
Could you please switch? ->curious to discover....and Find-out projects around you, thks

**Comment by madewild** [comment]
I don't think we can say "find out projects" in correct English... that's why I switched. To be checked.

**Comment by AThollard** [comment]
Find-out about?

**Comment by madewild** [comment]
Then why not simply "Find projects around you" ?
"Find out about projects around you" with 3 prepositions is really not elegant...

**Comment by AThollard** [comment]
ok

**Comment by madewild** [comment]
![Uploading car_final.png…]()
