### ISSUE TITLE
Add region polygon to project details

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#47]
When there is no coordinates, show polygon of region (NUTS3) instead of country

**Comment by madewild** [comment]
Duplicate of #24

**Comment by raphdom** [comment]
As dicussed with Dennis, when we don't have the coordinates we don't have the region also. Still need to check the lack of the data!

**Comment by D063520** [comment]
yes, this I have to fix ....

**Comment by madewild** [comment]
Is this feasible for Friday? Or do we postpone to v2?

**Comment by D063520** [comment]
I think this is feasible .... Thierry shared the mapping between program and nuts (I need to import them), the nuts are imported then it should be not difficult .....

**Comment by D063520** [comment]
But there is also the request to put the poligon when there is the geo-coordiante, and for this I already pass in the API the geoJson. So if you implement this, I need just to put the info in the API .....

**Comment by raphdom** [comment]
fixed
