### ISSUE TITLE
suggestion: would increase width of project view

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#475]
BEFORE (a bit small)

<img width="1680" alt="Screenshot 2022-02-16 at 22 10 47" src="https://user-images.githubusercontent.com/10883585/154357725-488d1343-4c25-4929-bc2a-47bf2bf9939c.png">

AFTER:

<img width="1680" alt="Screenshot 2022-02-16 at 22 11 56" src="https://user-images.githubusercontent.com/10883585/154357876-21dce3c0-43b5-4f70-b9fd-1426671a06c9.png">

Here the css that I changed:

<img width="1680" alt="Screenshot 2022-02-16 at 22 11 32" src="https://user-images.githubusercontent.com/10883585/154358007-75ef1f60-b607-4cf7-85f3-1aa52ccad131.png">

<img width="1680" alt="Screenshot 2022-02-16 at 22 11 47" src="https://user-images.githubusercontent.com/10883585/154358018-7367a98e-7517-4d69-bfc2-3b540cb5eeab.png">

PS: I would also set some min-width style .....

**Comment by raphdom** [comment]
nice, not easy with the responsive design (phone, tablet and desktop) sizes. But I've changed now and seems to be more big and nicer. Can you check @D063520?

**Comment by D063520** [comment]
Much better : )

**Comment by D063520** [comment]
Sorry .... only that now it changes from project to project:

LARGE
<img width="1680" alt="Screenshot 2022-02-17 at 14 27 38" src="https://user-images.githubusercontent.com/10883585/154491434-d2bdc537-8018-43e8-92f2-e9ffbf770cf4.png">

SMALL
<img width="1680" alt="Screenshot 2022-02-17 at 14 29 30" src="https://user-images.githubusercontent.com/10883585/154491556-1e3bc3ae-c10a-4444-a04e-323324fed985.png">


MEDIUM
<img width="1680" alt="Screenshot 2022-02-17 at 14 27 44" src="https://user-images.githubusercontent.com/10883585/154491589-c5c11a52-3091-4cde-b2ed-9036fc1c83ce.png">


Not sure if this is expected ....

**Comment by raphdom** [comment]
yeah, depending of the content, and the size of the screen, you don't like it, you are expecting something more fixed?

**Comment by D063520** [comment]
Yes, the previews one was fixed and I preferred it ....

**Comment by raphdom** [comment]
now should be fine, on dev... @madewild can you check?

**Comment by D063520** [comment]
looks fine to me
