### ISSUE TITLE
Remove link to linkedopendata.eu

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#48]
On project details page, the link after "Website" should go to the actual website of the beneficiary. If we don't have it, we display nothing. In any case we don't want a link to "linkedopendata.eu" here, it is already provided by edit button.

**Comment by raphdom** [comment]
The "link" data is coming in the API.
Should be change there, I already have the logic if we don't have the link display "n/a"

**Comment by madewild** [comment]
OK this is for Dennis then.
