### ISSUE TITLE
Adapt social media links on detail pages

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#480]
Current on https://kohesio.development.ec.europa.eu/projects/Q19822 we have this:
![sml](https://user-images.githubusercontent.com/942488/154417685-b5dd7f03-a40a-472a-8845-e5e7cecb2f71.png)

Some remarks:

- [x] Facebook should be before Twitter to respect the same order as the footer
- [x] Do we keep Instagram knowing that the URL is just https://instagram.com/ (no way to draft a post)?
- [x] Do we keep Linkedin ? (removed in the footer) -> yes
- [x] Adapt email

**Comment by gachpas** [comment]
@madewild ,

for what concerns Linkedin, I would keep it, as the purpose here is different, I (as a user) may want to share a project with a colleagues via Linkedin. I have double check with Slaven and he is aligned with this...so we can keep Linkedin.

When implemented, I will check the good functionning of all share, as for the meoment they are not availble §I assume that Raph is working on it) ;)

**Comment by madewild** [comment]
Sould be working on https://kohesio.development.ec.europa.eu/projects/Q19822, maybe you need to refresh the cache?

**Comment by gachpas** [comment]
@madewild,
The link to Linkedin and FB is working as expected (i.e. it opens the project page); for Insta, it did not copy any link, just opens the Insta homepage.....for twitter, I would not test, as I don't have an account :(
For the email, it still address the email to the FMB of REGIO EXT COM, while there should not be any recipient.
Br, Pascal

**Comment by madewild** [comment]
@gachpas for insta this is what I wrote above: there is no way to make it work like the other social media (or least least we did not find it, do you have a working example on another website?). If we cannot make it then it's a bit strange to leave just a link to insta homepage, so maybe we should remove the insta button.

For the mailto I will fix it with mailto:?subject=your%20subject&body=your%20body

**Comment by gachpas** [comment]
@madewild 
In this case, for Insta, I would remove it from the sharing possibilities...in any case, I do not really imagine nabila and co sharing a Kohesio project ;)
@AThollard , do you confirm that we can remove Insta?

**Comment by AThollard** [comment]
@gachpas could you please check this with Corinne and ask her how the insta link should work?
Btw, Insta is now massively used for institutional communication, and it covers much more than haircut and make-up pics :-)
Plus don't underestimate the power of Kohesio on Nabila :-)

**Comment by gachpas** [comment]
@AThollard , I had already asked Corinne before answering to Max ;) and she does not have example of other sites that pushes content to insta. She thinks that there is an Instagram policy preventing to do so. 
If so, as said by Max, there is no point in letting a link in the Share, while we cannot share ...

For what concerns purely content push to Insta, I find strange to push content as a Project page, while Insta is made for sharing pictures (which we do not have too much in Kohesio by now ;).....but maybe you can ask Nabila to make some free push for Kohesio? Has the Regional policy funded some Bio shampoo producing ;)

**Comment by gachpas** [comment]
@AThollard ,  in fact, thinking about it, it makes sense that Insta does not accept the push of other website pages, as its core business and concept is to share pictures that they want you to upload on their servers....make sense, no?

**Comment by madewild** [comment]
Now I know why GitHub is considered a social network by our analytics software! :laughing: 
![social_github](https://user-images.githubusercontent.com/942488/154472651-af4c054f-67ae-4c00-bdb5-4339e8994aca.png)

**Comment by madewild** [comment]
Should be better now, you can check on:
https://kohesio.development.ec.europa.eu/projects/Q19822
https://kohesio.development.ec.europa.eu/beneficiaries/Q197627

I hid Insta but can revert if necessary...

**Comment by gachpas** [comment]
@madewild  email ok now :) Thx

**Comment by madewild** [comment]
@AThollard can you confirm for insta? can we close?

**Comment by AThollard** [comment]
Amen. You can close

**Comment by madewild** [comment]
it will still be in the footer ;)

**Comment by AThollard** [comment]
what insta?

**Comment by gachpas** [comment]
@AThollard , yes, it is in the footer to lead to the EUinMyRegion inst page

**Comment by madewild** [comment]
https://kohesio.development.ec.europa.eu/
![insta_footer](https://user-images.githubusercontent.com/942488/154485923-77eeeb53-2b56-4b78-b90e-eb73262a0339.png)
