### ISSUE TITLE
Remove "in my region" and "themes" headers?

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#483]
Now that we have moved to ECL, do we want to keep these on the homepage or not?
If we keep them we should align the spacing before/after.

**Comment by raphdom** [comment]
I have aligned the spaces between all components in the homepage already.

**Comment by madewild** [comment]
@AThollard what is your view? we keep or remove?

**Comment by madewild** [comment]
In the end we keep them but I changed to h2 to have something a bit smaller.
