### ISSUE TITLE
facets cut

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#496]
see under temes

<img width="1680" alt="Screenshot 2022-02-17 at 14 25 49" src="https://user-images.githubusercontent.com/10883585/154491023-73ebe33e-ef7d-457f-8715-df2f2b624fa2.png">

**Comment by madewild** [comment]
In some cases we get a vertical scrollbar on both sides...
https://kohesio.development.ec.europa.eu/projects?keywords=Reconstruction%20of%20the%20NKP%20%E2%80%9COld%20Town%20Hall%E2%80%9D%20in%20T%C3%A1bor&sort=Total-Budget-(descending)

**Comment by madewild** [comment]
just one thing, when you go to https://kohesio.development.ec.europa.eu/projects?keywords=wifi&sort=Total-Budget-(descending) and press "Show Results", the sidepane is quite ugly/cut during the (short) loading time. Is there a quick fix for that?

**Comment by raphdom** [comment]
ah, I didn't count with the search terms, we have a margin, but I will increase, don't worry

**Comment by raphdom** [comment]
the things that only you find, lol

**Comment by madewild** [comment]
I still have a vertical scrollbar while the page is loading:
![loading_scroll](https://user-images.githubusercontent.com/942488/154696578-bcc24f80-6fb3-46fb-ab6f-7cc6a08ca77b.png)

**Comment by raphdom** [comment]
@madewild  can you check now?

**Comment by madewild** [comment]
Perfect!
