### ISSUE TITLE
projects nearby me, external regions are kept

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#497]
<img width="1680" alt="Screenshot 2022-02-17 at 14 37 38" src="https://user-images.githubusercontent.com/10883585/154492981-2053c0c1-506f-4659-8055-56c8aa4f6edc.png">

**Comment by madewild** [comment]
For me this is not such a problem... @AThollard do you think we should hid ethe ribbon in that case? Then what if someone hits projects near me from an outermost region? ;)

**Comment by madewild** [comment]
not so bad... Anne also says it can stay like that
@raphdom what do you think?

**Comment by D063520** [comment]
? For me it does not make sense .... if I'm in Auvergne and I search for projects nearby me, why should I see some other French islands?
