### ISSUE TITLE
new version cut's down more space

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#498]
I'm not sure if I was just used to the old one, but I feel that a lot of space is not taken by the new version. To compare

<img width="1680" alt="Screenshot 2022-02-17 at 14 41 35" src="https://user-images.githubusercontent.com/10883585/154493807-f6831789-519b-4310-92a3-2361aca0283f.png">

<img width="1680" alt="Screenshot 2022-02-17 at 14 41 29" src="https://user-images.githubusercontent.com/10883585/154493834-8d91f711-1eec-4451-850a-1defe6db445c.png">

**Comment by raphdom** [comment]
This is the size of the viewport on ECL, 1140px fixed, it will not grow. You can see that in all website from the commission. It is a standard. I like more the other one, with more space, anyway...
https://ec.europa.eu/info/index_en
https://ec.europa.eu/regional_policy/en/

**Comment by madewild** [comment]
Yeah nothing we can do about that unfortunately...
