### ISSUE TITLE
Reset map breadcrumb when clicking projects near me

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#504]
Navigating the map to a given NUTS level (lets say NUTS 3) then clicking "projects near me" will trigger the "projects near me" functionality but the "NUTS breadcrumb buttons" are not reset.

**Comment by madewild** [comment]
Example for me:
![pnm_bc](https://user-images.githubusercontent.com/942488/154576649-46cf5c92-60e5-4e86-8449-63d5c8c5c214.png)

**Comment by raphdom** [comment]
fixed on dev.

**Comment by madewild** [comment]
Great, fyi @djang0

**Comment by Djang0** [comment]
@madewild and @raphdom tested and fix is confirmed in DEV env. Thank you.
