### ISSUE TITLE
Pagination total slow to load

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#517]
Go to https://kohesio.development.ec.europa.eu/projects?sort=Total-Budget-(descending)
Select a big country and press "Show Results"
Projects are loaded immediately (cached) but the pagination total only appears after a small delay

Note: if I try again with the same country it works, seems that the total is also cached in that case

**Comment by raphdom** [comment]
I cannot reproduce it Max. I saw in your computer and I believe in you but I've try to reproduce and failed. :)

**Comment by madewild** [comment]
Let's try again tomorrow (or Monday) with a clean cache...

**Comment by madewild** [comment]
Mmmh not happening again today... will close and reopen if necessary.
