### ISSUE TITLE
Wrong bottom pagination for audiovisual

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#519]
https://kohesio.development.ec.europa.eu/projects?keywords=test&sort=Total-Budget-(descending)&page=3&tab=audiovisual
![av_bottom_pag](https://user-images.githubusercontent.com/942488/154674748-c09ab7c8-34d6-4b91-87dc-8e1a8b42845c.png)

Pagination below images is the one of projects!!

**Comment by madewild** [comment]
On the projects tab we have the pagination controller only at the top, we can do the same for AV and just remove it

**Comment by raphdom** [comment]
it was my fault. I moved the bottom paginator from the results to the audio visual tab. I moved back to the bottom to the results, should be fine now...
