### ISSUE TITLE
Mobile - beneficiary link does not appear on the project details

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio.eu#523]
@raphdom the beneficiary link does not appear at the end of the project details (mobile version)
If I open the project in a new tab, then it appears correctly

**Comment by AThollard** [comment]
It does not happen for all beneficiaries, the project details are troncated
![image](https://user-images.githubusercontent.com/80402472/154724707-cc0793ec-074e-449d-a6c7-523e8576e2cc.png)

**Comment by AThollard** [comment]
And yes in the modal over the map

**Comment by raphdom** [comment]
I agree, the modal on mobile sometimes cut the bottom of the information, we need to decrease the height of the modal

**Comment by raphdom** [comment]
this is done, now is much better the modal in mobile, I did some small improvements. Can you check @AThollard and @madewild ?

**Comment by raphdom** [comment]
The title on the top is needed when we scroll down, specially on mobile that we loose the title inside the content. For the scrollbar is indeed a bug

**Comment by madewild** [comment]
Then can we keep the top title only on mobile? Not critical of course...

**Comment by raphdom** [comment]
Not easy, depend of the height on desktop and sometimes we have a big description that need the scroll even on desktop. I left the title and fix the scroll, can you check @madewild ?

**Comment by madewild** [comment]
OK!
