### ISSUE TITLE
Reset filters does not work properly

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#533]
Go to https://kohesio.development.ec.europa.eu/projects
Select a theme (e.g. "Research & Innovation")
Click "Show results"
Click "Reset Filters"
Policy is reset but not Theme

**Comment by madewild** [comment]
Other example:

Got to https://kohesio.development.ec.europa.eu/projects
Select a country (e.g. Austria)
Click "Show results"
Click "Reset Filters"
Region list is reset but not country

Probably linked to filters interaction

**Comment by raphdom** [comment]
fixed
