### ISSUE TITLE
Enhancement - desktop version projects list

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio.eu#538]
Results/Audiovisual/Map tabs: if possible align the font size and color with the filter names on the left + reduce the blank space on top
![image](https://user-images.githubusercontent.com/80402472/154914450-546eac22-e47b-4ebb-985f-abb48ee94c2a.png)

**Comment by madewild** [comment]
Yes exactly, I would not touch this.
The typography of the tabs names seems aligned with the pagination, easy way to tweak this? For me it's good enough as it is...

**Comment by raphdom** [comment]
I will increase the font-size of the tabs.

**Comment by AThollard** [comment]
fine with me if we just touche the font-size

**Comment by raphdom** [comment]
done
