### ISSUE TITLE
Warning when leaving to Wikidata

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#54]
When we click on a Wikidata link, we should somehow warn the user that we are leaving the Commission-approved data. This is especially important since Wikidata looks very much like our Wikibase (linkedopendata.eu). People should not be misled as to whether the information is approved by the Commission or not.

Any user-friendly way of achieving that?

**Comment by madewild** [comment]
@weisest could R4 also help with a disclaimer in this case?

**Comment by madewild** [comment]
The suggested phrasing is “Please note that you are now leaving the Kohesio website from the European Commission. The EC cannot be held responsible for incorrect information published on Wikidata" 
@weisest will cross-check with D4

**Comment by raphdom** [comment]
done, waiting for @weisest confirmation to change or not the message

**Comment by weisest** [comment]
Reply from D4, there is no official wording so this is fine but we should change "incorrect" with "any" 
“Please note that you are now leaving the Kohesio website from the European Commission. The EC cannot be held responsible for any information published on Wikidata"
