### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#56]
As the URL is now shared with many people, it becomes urgent to fill the About page (https://kohesio.eu/about) with some context about the scope of the pilot, why we only have 6 member states, etc.
@teodoracostin could you press REGIO for the content to be included on this page?
If a random citizen arrives on kohesio.eu it is not very clear why some countries are absent...

**Comment by teodoracostin** [comment]
Email sent to Pascal.

**Comment by teodoracostin** [comment]
Content added.
