### ISSUE TITLE
Update key figures

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#66]
On homepage:
* Number of projects: 705 095
* Number of beneficiaries: 122 504
* Total EU Amount: 114 728 800 218

The amount needs to be cross-checked because apparently it suprised the directors... And some people also think it's not a good idea to display the total money on the homepage so perhaps we need to replace with another key figure.

**Comment by madewild** [comment]
I cross-checked everything and the total amount seems correct
The explanation is probably that Poland has a lot of high-amount projects and is pushing the total upwards.

**Comment by raphdom** [comment]
We don't understand what we should do here...

**Comment by madewild** [comment]
Please update the numbers on homepage, they are no longer correct (we have more projects etc now)

**Comment by D063520** [comment]
Hola! I made an API for this at "api/dev/facet/eu/statistics". With this it will be always up to date .... the result will be cached so it will e the same until we do not invalidate the cache

**Comment by raphdom** [comment]
done, it was implemented on the homepage
