### ISSUE TITLE
Pagination + count

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#7]
Add pagination and total number of projects
120 projects (10 pages of 12) is a good start for now

**Comment by raphdom** [comment]
Pagination on client side is done, I am not sure if you want to close this?

**Comment by madewild** [comment]
Do you think it's better to have 10 per page instead of 12 ? Then maybe adapt the display...

**Comment by raphdom** [comment]
12,24,48,96?

**Comment by madewild** [comment]
I agree it's a bit strange... but the two blank spaces as well so maybe lines of 5 is better

**Comment by raphdom** [comment]
okay, I changed to 15,30,60 and the lines I change to 1,2,3,5 according to the size of the screen...

**Comment by madewild** [comment]
Looks good to me so I close for now, thanks
