### ISSUE TITLE
Program adapting to country

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#74]
Quote by Thierry:

"The advanced filters don’t adapt dynamically to the global filters.  This is particularly visible for the “Programme name” which is a data typically linked to the country.  When browsing the French projects, only the French programmes should be selectable and so on."

This is possible, the API for the program:

/facet/eu/programs

has an optional parameter country. So if the country is set, just set also the parameter for the program ....

**Comment by raphdom** [comment]
done
