### ISSUE TITLE
Programming period

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#75]
Quote by Theirry:

"Programming period: currently, we only have ingested projects from 2014-2020, although the filter shows only value 2021 - 2027.  Moreover this value doesn’t empty when the filters are reset.  Both “2014 - 2020” and “2021 - 2027” should be presented, with the possibility to have no (=blank) selection."

We should for sure change 2021 - 2027 to 2014 - 2020. If you can, can you make the results empty if "2021 - 2027". It's more like a hak ....

**Comment by raphdom** [comment]
done
