### ISSUE TITLE
Intervention Field by area ...

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#76]
Intervention Field: the sorting by alphabetical order makes it hard to select a correct target.  Originally, the intervention fields are classified by areas:
![image003](https://user-images.githubusercontent.com/10883585/88328596-fd489600-cd28-11ea-994e-91c9b4c69653.png)
Is it possible to have the areas (in grey in the screenshot above) somehow separating the intervention fields, and the intervention fields classified under them ?  Possibly, having the intervention fields shown with their codes in front would help classifying.

**Comment by madewild** [comment]
Yes, this asks for improvement...

**Comment by madewild** [comment]
Another idea suggested by Anne is to have expanding dropdowns that open with a + sign the subcontents of categories. This could also be used for regions and subregions but I don't know if this fits well in the current dropdowns...

**Comment by madewild** [comment]
@D063520 does the API support more than one CoI at the same time?

**Comment by raphdom** [comment]
@D063520 the API to get the intervention field, should give me the parent and children also
https://kohesio.linkedopendata.eu/api/dev/facet/eu/categoriesOfIntervention
in order to build the relations

**Comment by madewild** [comment]
API not yet ready so we postpone.

**Comment by madewild** [comment]
@D063520 is this ready in the backend? I don't remember...

**Comment by madewild** [comment]
ah it's described in https://github.com/ec-doris/kohesio.eu/issues/208
@raphdom please review and validate when you have time...

**Comment by raphdom** [comment]
fixed on dev, please test

**Comment by madewild** [comment]
perfect for me!
