### ISSUE TITLE
Themes filter doesn't work properly

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#91]
When we select, in the projects page one theme, the results are without the theme that we've selected.

**Comment by D063520** [comment]
can you describe the problem better ... I tried the first theme (Climate Change Adaptation & Risk Prevention) and for me it is right ..... note the themes are associeted to the categories of intervention ....

**Comment by raphdom** [comment]
Pascal told me that always when we select a theme, the first pages is always with "Category of intervention not declared by the Managing Authority" but I remember that was not like that before, when we did the selection this appear the themes in the first page...

**Comment by D063520** [comment]
yes, there was a bug introduced for some reason ; )
