### ISSUE TITLE
Typo in about page

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#94]
Check the last sentence here:

https://dev.kohesio.eu/about

At the moment, Kohesio is still in its pilot phase and is presenting therefore data limited to 6 pilot Member States: Czechia, Danemark, France, Ireland, Italy and Poland.

I think it should be Czech Republic and Denmark is misselled

**Comment by madewild** [comment]
For Czechia vs Czech Republic it's not so straightforward: https://en.wikipedia.org/wiki/Name_of_the_Czech_Republic
I have seen both in use at the Commission (and it already created some problems in the past) but I agree we should settle for one name everywhere. Let's ask the Czech delegates in September what they prefer :)

**Comment by madewild** [comment]
Please put I Czech Republic and Denmark for now

**Comment by raphdom** [comment]
done
