### ISSUE TITLE
Create test env

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#95]
Between dev and prod

**Comment by D063520** [comment]
wait ... you mean having prod, dev and now test?

**Comment by madewild** [comment]
Yes, not urgent but we need an environment where REGIO (and later member states) can test new features before deploying them to prod, but dev is not the right place to do that, it should be only for developers. This is standard IT management. :)

**Comment by madewild** [comment]
PS: DIGIT tools have 5 environments, DEV TEST ACC MAINT and PROD ;)

**Comment by D063520** [comment]
I created test in the backend .... available at "/api/test". But what should I put there? Currently it is an older version of dev ..... A bit insecure about this .....

**Comment by madewild** [comment]
Right now you can put the same as dev. But when we merge dev the next time (next Thursday), we will merge into test instead of merging directly into prod to avoid breaking the prod. Then after REGIO review we can merge test into prod. Clearer? :)

**Comment by D063520** [comment]
ok, I got it!

**Comment by madewild** [comment]
Let's discuss with WMDE in January to see how they manage this in Wikidata

**Comment by madewild** [comment]
@raphdom could you add a test env in the frontend to link the test api?

**Comment by madewild** [comment]
linked to https://github.com/ec-doris/kohesio-backend/issues/64
will be solved in EKS

**Comment by madewild** [comment]
Soon on https://kohesio.test.ec.europa.eu/ ...
