### ISSUE TITLE
Add licence for search around a point

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#96]
This product includes GeoLite2 data created by MaxMind, available from
<a href="https://www.maxmind.com">https://www.maxmind.com</a>.

**Comment by madewild** [comment]
@D063520 do we send any data outside (through an API) for this or just resolve the location locally?

**Comment by D063520** [comment]
I prepared that, I will push it when raph gives me the go ....

**Comment by raphdom** [comment]
done
