### ISSUE TITLE
Changed map API

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#97]
Hi,

I changed the map API. 

1) If you query:

curl -G 'localhost:5678/api/dev/facet/eu/search/project/map'   --data-urlencode 'keywords=angola'

you will get (when there are less than 2000 results or the nuts region is already the smallest) a list of geo corrdinates
                                                                                       
{"geoJson":"","list":["16.1976,51.0677","12.2018,44.4161","17.2906,50.9574"]}

To get the projects at a specific coordinate you then call:

curl -G 'localhost:5678/api/dev/facet/eu/search/project/map/**point**' --data-urlencode 'coordinate=17.2906,50.9574'  --data-urlencode 'keywords=angola'

to get a list of the projects:

[{"item":"https://linkedopendata.eu/entity/Q94610","label":"The internationalisation of the company Ddex- Konstrums of Stalowa."}]

i.e. you pass the exactly same parameters as the previous request (filters, keywords program and so on) + the coordinate

**Comment by raphdom** [comment]
Implemented. On dev!
