### ISSUE TITLE
Made API for image

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#98]
I added an API for the image search. The parameters are the same as the other search APIs

curl -G 'localhost:5678/api/dev/facet/eu/search/project/image' --data-urlencode 'keywords=blood glucose'

gives back:

{"numberResults":1,"list":[{"image":"https://ec.europa.eu/regional_policy/rest/projects/upload/regio_standard_153_4078_mellisim_image.jpg","item":"https://linkedopendata.eu/entity/Q139379"}]}

NOTE: When there is no result there should be written, No Audio Visual Documents found, or something like this ....., because there might be results for the search, only not audio visual ones!

**Comment by raphdom** [comment]
done! implemented, event the "no results"
